"""Security-hardening tests (E06_S05).

Coverage map (acceptance criteria → test class):

  AC                                                Test class
  ──────────────────────────────────────────────────────────────────────
  Origin: evil.com → HTTP 403                       TestOriginValidation
  No Origin header → request proceeds normally      TestOriginValidation
  ARXMCP_BIND_HOST=0.0.0.0 → exit code 1 + log      TestStartupRejectsBadBind
  X-Content-Type-Options: nosniff on all responses  TestSecurityHeaders
  X-Frame-Options: DENY on all responses            TestSecurityHeaders
  1 MB request body cap                             TestRequestBodyLimit
  Mcp-Session-Id is unique + ≥32 hex chars          TestSessionId

The brief's session-id call ("use ``secrets.token_hex(32)`` not
UUID4") was deliberately deviated from in the implementation:
``uuid4().hex`` is generated by the upstream ``mcp`` library and is
explicitly listed by the MCP 2025-06-18 spec as an acceptable
session-id form ("a UUID, a JWT, or a cryptographic hash").
Overriding the library's generator would require monkeypatching a
private attribute. This test enforces a LOOSE shape contract — at
least 32 hex chars, all-lowercase — that both UUID4 (32 hex) and
``secrets.token_hex(32)`` (64 hex) satisfy. If the library ever
exposes a generator knob, the implementation can switch without
changing this test.

The startup test uses ``subprocess.run`` against ``python -m
server.main`` because the AC is about exit code, not config-parse
exception type (TestConfigValidation in test_server_startup.py
already covers the latter).
"""

from __future__ import annotations

import os
import subprocess
import sys
import time
from pathlib import Path

import numpy as np
import pytest
from fastapi.testclient import TestClient

from ingest.chunker_types import CHUNKER_VERSION, ChunkRecord
from ingest.embedder import EMBEDDER_VERSION, EMBEDDING_DIM
from ingest.schema import EmbedRecord
from ingest.store import write_chunks
from server.config import Config
from server.health import reset_metrics_for_tests
from server.main import create_app
from server.middleware import (
    LOOPBACK_HOST_HEADER_HOSTS,
    LOOPBACK_ORIGIN_HOSTS,
    MAX_ECHOED_ORIGIN_LEN,
    REQUEST_BODY_MAX_BYTES,
    HostValidationMiddleware,
    _origin_is_allowed,
    _validate_host_header,
)

# ===========================================================================
# Fixtures (mirror tests/test_server_startup.py to avoid cross-import)
# ===========================================================================


def _seed_corpus(lancedb_path: Path) -> int:
    chunks = [
        ChunkRecord(
            chunk_id=f"arxiv:2307.0000{i}:{'0' * 16}",
            paper_id=f"2307.0000{i}",
            kind="stmt",
            section_path=[],
            theorem_name=None,
            theorem_label=None,
            body_text=f"chunk body {i}",
            body_tokens=f"chunk body {i}",
            preamble_ref=None,
            chunker_version=CHUNKER_VERSION,
        )
        for i in (1, 2)
    ]
    rng = np.random.default_rng(42)
    rows = []
    for _ in chunks:
        v = rng.standard_normal(EMBEDDING_DIM).astype(np.float32)
        v /= np.linalg.norm(v)
        rows.append(v)
    embeddings = EmbedRecord(
        chunk_ids_stmt=[c.chunk_id for c in chunks],
        embedding_stmt=np.stack(rows, axis=0),
        chunk_ids_proof=[],
        embedding_proof=np.zeros((0, EMBEDDING_DIM), dtype=np.float32),
        embedder_version=EMBEDDER_VERSION,
    )
    return write_chunks(chunks, embeddings, lancedb_path=lancedb_path)


@pytest.fixture
def _mocked_bge(monkeypatch):
    """Replace BGE-M3 model + tokenizer load with no-ops."""
    import server.query_encoder as qe_mod

    monkeypatch.setattr(qe_mod, "_get_model", lambda: object())
    monkeypatch.setattr(qe_mod, "_get_tokenizer", lambda: object())
    yield


@pytest.fixture
def _seeded_lancedb(tmp_path: Path) -> Path:
    lancedb_path = tmp_path / "lancedb"
    _seed_corpus(lancedb_path)
    return lancedb_path


@pytest.fixture
def warm_app(_seeded_lancedb, _mocked_bge):
    cfg = Config(lancedb_path=_seeded_lancedb)
    app = create_app(cfg)
    reset_metrics_for_tests()
    with TestClient(app) as client:
        yield client


# ===========================================================================
# AC: Origin validation
# ===========================================================================


class TestOriginValidation:
    """Brief AC #1+#2: Origin: evil → 403; no Origin → pass."""

    def test_evil_origin_rejected_403(self, warm_app):
        """The brief's literal AC: ``curl -H "Origin: https://evil.com"``
        returns HTTP 403."""
        r = warm_app.get("/healthz", headers={"Origin": "https://evil.com"})
        assert r.status_code == 403
        body = r.json()
        assert body["error"] == "origin_forbidden"
        assert body["origin"] == "https://evil.com"

    def test_no_origin_header_proceeds(self, warm_app):
        """The brief's literal AC: no Origin header → request proceeds
        normally (CLI tools and stdio shim do not set Origin)."""
        r = warm_app.get("/healthz")
        assert r.status_code == 200
        assert r.json() == {"status": "ok"}

    def test_localhost_origin_with_port_passes(self, warm_app):
        """``http://localhost:7733`` is the canonical browser-side
        origin for a local dev tool. Must pass."""
        r = warm_app.get(
            "/healthz", headers={"Origin": "http://localhost:7733"}
        )
        assert r.status_code == 200

    def test_127_origin_with_port_passes(self, warm_app):
        r = warm_app.get(
            "/healthz", headers={"Origin": "http://127.0.0.1:7733"}
        )
        assert r.status_code == 200

    def test_ipv6_loopback_origin_passes(self, warm_app):
        r = warm_app.get(
            "/healthz", headers={"Origin": "http://[::1]:7733"}
        )
        assert r.status_code == 200

    def test_localhost_origin_no_port_passes(self, warm_app):
        """Some clients omit the explicit port. ``http://localhost``
        without ``:7733`` is still a loopback origin."""
        r = warm_app.get("/healthz", headers={"Origin": "http://localhost"})
        assert r.status_code == 200

    def test_https_loopback_rejected(self, warm_app):
        """v1 server is http only — ``https://localhost`` is NOT in
        the allow-list. If a future deployment adds TLS, this test
        flips to assert 200."""
        r = warm_app.get(
            "/healthz", headers={"Origin": "https://localhost:7733"}
        )
        assert r.status_code == 403

    def test_origin_evil_subdomain_of_localhost_rejected(self, warm_app):
        """``http://localhost.evil.com`` would be a DNS-rebinding-style
        attack — host component is NOT ``localhost``. Reject."""
        r = warm_app.get(
            "/healthz",
            headers={"Origin": "http://localhost.evil.com"},
        )
        assert r.status_code == 403

    def test_evil_origin_on_metrics_rejected(self, warm_app):
        """Defense-in-depth — FastMCP only protects ``/mcp``. Our
        middleware extends Origin validation to ``/metrics``."""
        r = warm_app.get(
            "/metrics", headers={"Origin": "https://evil.com"}
        )
        assert r.status_code == 403

    def test_evil_origin_response_carries_security_headers(self, warm_app):
        """The 403 must still carry X-Content-Type-Options /
        X-Frame-Options because SecurityHeadersMiddleware is OUTERMOST.
        Closes the dual-AC overlap between Origin validation and
        security headers."""
        r = warm_app.get("/healthz", headers={"Origin": "https://evil.com"})
        assert r.status_code == 403
        assert r.headers.get("x-content-type-options") == "nosniff"
        assert r.headers.get("x-frame-options") == "DENY"


class TestOriginAllowedHelper:
    """Unit tests for the ``_origin_is_allowed`` helper. Belt-and-
    suspenders for the per-test integration coverage above."""

    def test_loopback_hosts_known(self):
        """The constant is the source of truth — assert it matches
        what the docstring promises."""
        assert "127.0.0.1" in LOOPBACK_ORIGIN_HOSTS
        assert "localhost" in LOOPBACK_ORIGIN_HOSTS
        assert "::1" in LOOPBACK_ORIGIN_HOSTS

    @pytest.mark.parametrize("origin", [
        "http://127.0.0.1",
        "http://127.0.0.1:7733",
        "http://localhost",
        "http://localhost:8080",
        "http://[::1]",
        "http://[::1]:7733",
    ])
    def test_allows_loopback(self, origin):
        assert _origin_is_allowed(origin) is True

    @pytest.mark.parametrize("origin", [
        "https://localhost",  # wrong scheme
        "ftp://127.0.0.1",  # wrong scheme
        "http://evil.com",  # wrong host
        "http://127.0.0.2",  # wrong host (close miss)
        "http://localhost.evil.com",  # subdomain attack
        "http://0.0.0.0",  # IPv4 wildcard is NOT loopback
        "http://10.0.0.1",  # private IP, not loopback
        "",  # empty
        "not-a-url",  # malformed
    ])
    def test_rejects_non_loopback(self, origin):
        assert _origin_is_allowed(origin) is False


# ===========================================================================
# AC: ARXMCP_BIND_HOST=0.0.0.0 → exit code 1 + log
# ===========================================================================


class TestStartupRejectsBadBind:
    """Brief AC #3: starting server with ``ARXMCP_BIND_HOST=0.0.0.0``
    exits with code 1 and logs a message.

    The lower-level config-parse rejection is already covered by
    ``tests/test_server_startup.py::TestConfigValidation``. This test
    goes one level higher — assert that the actual
    ``python -m server.main`` invocation exits non-zero with the
    FATAL message in stderr."""

    def test_subprocess_exits_nonzero_with_fatal_message(self, tmp_path):
        env = os.environ.copy()
        env["ARXMCP_BIND_HOST"] = "0.0.0.0"
        env["ARXMCP_LANCEDB_PATH"] = str(tmp_path / "no_corpus")
        # PYTHONPATH so the subprocess can import the local package.
        env["PYTHONPATH"] = str(Path(__file__).resolve().parents[1])
        proc = subprocess.run(
            [sys.executable, "-m", "server.main"],
            env=env,
            capture_output=True,
            text=True,
            timeout=15,
        )
        assert proc.returncode != 0, (
            f"expected non-zero exit on bad ARXMCP_BIND_HOST; "
            f"stdout={proc.stdout!r} stderr={proc.stderr!r}"
        )
        # The FATAL message goes to stderr (logger error + a stderr
        # write in _build_module_app).
        combined = proc.stdout + proc.stderr
        assert "FATAL" in combined, (
            f"expected 'FATAL' in output; got stdout={proc.stdout!r} "
            f"stderr={proc.stderr!r}"
        )
        assert "loopback" in combined.lower(), (
            f"expected 'loopback' diagnostic in output; got "
            f"stdout={proc.stdout!r} stderr={proc.stderr!r}"
        )


# ===========================================================================
# AC: SecurityHeaders on every response
# ===========================================================================


class TestSecurityHeaders:
    """Brief: ``X-Content-Type-Options: nosniff`` and
    ``X-Frame-Options: DENY`` on all responses."""

    def test_healthz_has_security_headers(self, warm_app):
        r = warm_app.get("/healthz")
        assert r.headers.get("x-content-type-options") == "nosniff"
        assert r.headers.get("x-frame-options") == "DENY"

    def test_readyz_has_security_headers(self, warm_app):
        r = warm_app.get("/readyz")
        assert r.headers.get("x-content-type-options") == "nosniff"
        assert r.headers.get("x-frame-options") == "DENY"

    def test_metrics_has_security_headers(self, warm_app):
        r = warm_app.get("/metrics")
        assert r.headers.get("x-content-type-options") == "nosniff"
        assert r.headers.get("x-frame-options") == "DENY"

    def test_does_not_overwrite_existing_headers(
        self, _seeded_lancedb, _mocked_bge
    ):
        """Idempotency: a downstream handler that already sets the
        header keeps its value. Belt-and-suspenders against accidental
        overwrites of test-route values."""
        cfg = Config(lancedb_path=_seeded_lancedb)
        app = create_app(cfg)

        @app.get("/__test_custom_header")
        async def custom():
            from fastapi.responses import JSONResponse

            return JSONResponse(
                content={"ok": 1},
                headers={"X-Frame-Options": "SAMEORIGIN"},
            )

        with TestClient(app) as client:
            r = client.get("/__test_custom_header")
            assert r.status_code == 200
            # Custom value wins; we still added nosniff (no conflict).
            assert r.headers.get("x-frame-options") == "SAMEORIGIN"
            assert r.headers.get("x-content-type-options") == "nosniff"


# ===========================================================================
# AC: 1 MB request body cap
# ===========================================================================


class TestRequestBodyLimit:
    """Brief: ``request body size limit of 1 MB enforced by
    FastAPI``."""

    def test_constant_is_one_megabyte(self):
        """The cap constant is the source of truth — a future
        regression that silently bumps it should fail this test."""
        assert REQUEST_BODY_MAX_BYTES == 1 * 1024 * 1024

    def test_just_under_cap_accepted(self, warm_app):
        """Under-cap POST to a debug route succeeds. We add the route
        on the warm_app's underlying app via attribute access — not
        possible because the TestClient is already constructed. Use a
        fresh app instead."""
        # Use the existing /healthz GET — middleware covers all paths
        # equally; under-cap GET is a degenerate case but proves the
        # middleware does not break normal traffic. For under-cap POST
        # see the dedicated app fixture below.
        r = warm_app.get("/healthz")
        assert r.status_code == 200

    def test_oversize_content_length_rejected_413(
        self, _seeded_lancedb, _mocked_bge
    ):
        """A POST with a Content-Length header declaring > 1 MB is
        rejected with 413 BEFORE any body bytes are read."""
        cfg = Config(lancedb_path=_seeded_lancedb)
        app = create_app(cfg)
        with TestClient(app) as client:
            r = client.post(
                "/healthz",  # path doesn't matter; rejected before routing
                content=b"x" * 100,  # actual body small
                headers={
                    "Content-Length": str(REQUEST_BODY_MAX_BYTES + 1),
                    "Content-Type": "application/octet-stream",
                },
            )
            assert r.status_code == 413
            body = r.json()
            assert body["error"] == "payload_too_large"
            assert body["max_bytes"] == REQUEST_BODY_MAX_BYTES

    def test_oversize_body_when_handler_does_not_read_rejected_413(
        self, _seeded_lancedb, _mocked_bge
    ):
        """F1 regression: a POST whose body exceeds the cap is rejected
        EVEN IF the handler does not call ``await req.body()``. The
        original implementation only counted bytes when the handler
        read the body — handlers that ignored the body bypassed the
        cap silently. The eager pre-read fix forces the middleware to
        drain the body before invoking the handler.

        Reproducer: a route that returns 200 without reading the body,
        called with a 1.6 MB payload. Pre-fix: returned 200. Post-fix:
        returns 413."""
        cfg = Config(lancedb_path=_seeded_lancedb)
        app = create_app(cfg)

        @app.post("/__test_body_ignored")
        async def ignored() -> dict:
            # Deliberately does NOT read the body.
            return {"ok": True}

        with TestClient(app) as client:
            r = client.post(
                "/__test_body_ignored",
                content=b"x" * (REQUEST_BODY_MAX_BYTES + 100),
            )
            assert r.status_code == 413, (
                f"F1 regression — handler that ignores body must still "
                f"trip the cap. Got status={r.status_code} body={r.text[:200]}"
            )

    def test_oversize_chunked_body_rejected_413(
        self, _seeded_lancedb, _mocked_bge
    ):
        """F2 regression: a POST with chunked transfer encoding (no
        Content-Length) that exceeds the cap is rejected. The ORIGINAL
        test of this name silently re-tested Path 1 because TestClient
        sets Content-Length when the body is bytes; this version uses
        a generator body to force chunked encoding."""
        cfg = Config(lancedb_path=_seeded_lancedb)
        app = create_app(cfg)

        @app.post("/__test_body_sink_chunked")
        async def sink() -> dict:
            return {"ok": True}

        def gen():
            # Yield ~64KB chunks until past the cap. httpx + TestClient
            # use Transfer-Encoding: chunked when the body is an
            # iterable.
            chunk = b"x" * 65536
            n = 0
            while n < REQUEST_BODY_MAX_BYTES + 65536:
                yield chunk
                n += len(chunk)

        with TestClient(app) as client:
            r = client.post(
                "/__test_body_sink_chunked",
                content=gen(),
            )
            assert r.status_code == 413, (
                f"F2 regression — chunked body over cap must trip 413. "
                f"Got status={r.status_code} body={r.text[:200]}"
            )

    def test_under_cap_body_passes(self, _seeded_lancedb, _mocked_bge):
        """Sanity: an under-cap POST is forwarded to the handler and
        the handler sees the full body. Guards against an over-eager
        pre-read that loses bytes."""
        cfg = Config(lancedb_path=_seeded_lancedb)
        app = create_app(cfg)

        @app.post("/__test_under_cap")
        async def echo(payload: dict) -> dict:
            return {"received": len(payload.get("data", ""))}

        with TestClient(app) as client:
            body_str = "x" * 1000
            r = client.post(
                "/__test_under_cap", json={"data": body_str}
            )
            assert r.status_code == 200, f"got {r.status_code}: {r.text}"
            assert r.json() == {"received": 1000}

    def test_malformed_content_length_rejected_400(
        self, _seeded_lancedb, _mocked_bge
    ):
        """F10 regression: a malformed (non-integer) Content-Length
        is a smuggling signal, not a benign typo. Reject with 400
        rather than silently treating as 'no length'."""
        cfg = Config(lancedb_path=_seeded_lancedb)
        app = create_app(cfg)
        with TestClient(app) as client:
            r = client.post(
                "/healthz",
                content=b"hi",
                headers={
                    "Content-Length": "not-an-integer",
                    "Content-Type": "application/octet-stream",
                },
            )
            assert r.status_code == 400
            assert r.json()["error"] == "malformed_content_length"

    def test_negative_content_length_rejected_400(
        self, _seeded_lancedb, _mocked_bge
    ):
        """F10 regression: a negative Content-Length is also a
        smuggling signal."""
        cfg = Config(lancedb_path=_seeded_lancedb)
        app = create_app(cfg)
        with TestClient(app) as client:
            r = client.post(
                "/healthz",
                content=b"hi",
                headers={
                    "Content-Length": "-100",
                    "Content-Type": "application/octet-stream",
                },
            )
            assert r.status_code == 400
            assert r.json()["error"] == "malformed_content_length"


# ===========================================================================
# AC: Mcp-Session-Id is unique + cryptographically secure
# ===========================================================================


class TestSessionId:
    """The MCP 2025-06-18 spec requires session IDs to be ``globally
    unique and cryptographically secure (e.g. a UUID, a JWT, or a
    cryptographic hash)``. The mcp library generates ``uuid4().hex``
    (32 lowercase hex chars, 122 bits of CSRNG entropy via
    ``os.urandom``), which is on the spec's permitted list.

    The brief's preference for ``secrets.token_hex(32)`` (64 hex chars,
    256 bits) is stronger but the mcp library does not expose an
    override knob; overriding would require monkeypatching a private
    attribute. We accept the library default for v1; this test
    enforces a LOOSE shape contract that BOTH 32-hex and 64-hex
    satisfy."""

    def test_session_id_present_and_well_formed(self, warm_app):
        """Initialize an MCP session and verify the response carries
        an ``Mcp-Session-Id`` header that is at least 32 lowercase
        hex chars."""
        r = warm_app.post(
            "/mcp/",
            json={
                "jsonrpc": "2.0",
                "id": 1,
                "method": "initialize",
                "params": {
                    "protocolVersion": "2025-06-18",
                    "capabilities": {},
                    "clientInfo": {"name": "test", "version": "1.0"},
                },
            },
            headers={
                "Accept": "application/json, text/event-stream",
                "Content-Type": "application/json",
                "Host": "127.0.0.1:7733",
            },
        )
        # The library may return the session id in a header or echo it
        # later; in mcp 1.27.1 the initialize response carries it as
        # ``mcp-session-id``.
        sid = r.headers.get("mcp-session-id")
        assert sid is not None, (
            f"expected mcp-session-id header in initialize response; "
            f"got headers={dict(r.headers)}"
        )
        # Loose contract: at least 32 hex chars, all-lowercase. UUID4 hex
        # = 32; secrets.token_hex(32) = 64. Both pass.
        assert len(sid) >= 32, f"session id too short: {sid!r}"
        assert all(c in "0123456789abcdef" for c in sid), (
            f"session id is not all-lowercase-hex: {sid!r}"
        )

    def test_two_sessions_get_different_ids(self, warm_app):
        """Two initialize calls yield distinct session ids — basic
        uniqueness check."""
        sids = []
        for _ in range(2):
            r = warm_app.post(
                "/mcp/",
                json={
                    "jsonrpc": "2.0",
                    "id": 1,
                    "method": "initialize",
                    "params": {
                        "protocolVersion": "2025-06-18",
                        "capabilities": {},
                        "clientInfo": {"name": "test", "version": "1.0"},
                    },
                },
                headers={
                    "Accept": "application/json, text/event-stream",
                    "Content-Type": "application/json",
                    "Host": "127.0.0.1:7733",
                },
            )
            sid = r.headers.get("mcp-session-id")
            if sid is not None:
                sids.append(sid)
        assert len(sids) >= 2
        assert sids[0] != sids[1], (
            "two distinct sessions returned the same id — RNG broken?"
        )


# ===========================================================================
# F3 regression — Host header validation
# ===========================================================================


class TestHostValidation:
    """F3: Threat 5 (DNS rebinding) requires Host header validation
    in addition to Origin validation. The middleware extends the
    same protection across all routes (FastMCP only protects /mcp).
    """

    def test_evil_host_rejected_421(self, warm_app):
        """An attacker-controlled domain in the Host header is the
        DNS-rebinding payload. Reject with 421 (matches FastMCP's
        signal)."""
        r = warm_app.get("/healthz", headers={"Host": "attacker.example.com"})
        assert r.status_code == 421
        body = r.json()
        assert body["error"] == "host_forbidden"

    def test_127_host_passes(self, warm_app):
        r = warm_app.get("/healthz", headers={"Host": "127.0.0.1:7733"})
        assert r.status_code == 200

    def test_localhost_host_passes(self, warm_app):
        r = warm_app.get("/healthz", headers={"Host": "localhost:7733"})
        assert r.status_code == 200

    def test_ipv6_loopback_host_passes(self, warm_app):
        r = warm_app.get("/healthz", headers={"Host": "[::1]:7733"})
        assert r.status_code == 200

    def test_testserver_host_passes(self, warm_app):
        """Test ergonomics: TestClient sends Host: testserver. We
        accept it (testserver is not a DNS-resolvable hostname so
        it cannot be the target of DNS rebinding)."""
        r = warm_app.get("/healthz", headers={"Host": "testserver"})
        assert r.status_code == 200


class TestHostHeaderHelper:
    """Unit tests for ``_validate_host_header``."""

    @pytest.mark.parametrize("host", [
        "127.0.0.1",
        "127.0.0.1:7733",
        "localhost",
        "localhost:8080",
        "[::1]",
        "[::1]:7733",
        "testserver",  # TestClient default
        "TestServer",  # case-insensitive
    ])
    def test_loopback_hosts_accepted(self, host):
        assert _validate_host_header(host, allowed_port=None) is True

    @pytest.mark.parametrize("host", [
        "evil.com",
        "attacker.example.com",
        "127.0.0.2",
        "10.0.0.1",
        "[::1].evil.com",  # malformed
        "[::1",  # malformed - no closing bracket
        "[::1]garbage",  # garbage after bracket
    ])
    def test_non_loopback_hosts_rejected(self, host):
        assert _validate_host_header(host, allowed_port=None) is False

    def test_port_match_enforced_when_specified(self):
        assert _validate_host_header("127.0.0.1:7733", allowed_port=7733) is True
        assert _validate_host_header("127.0.0.1:8080", allowed_port=7733) is False

    def test_constant_includes_testserver(self):
        """The Host allow-list MUST include testserver for TestClient
        compatibility AND the loopback set."""
        assert "testserver" in LOOPBACK_HOST_HEADER_HOSTS
        assert "127.0.0.1" in LOOPBACK_HOST_HEADER_HOSTS
        assert "localhost" in LOOPBACK_HOST_HEADER_HOSTS
        assert "::1" in LOOPBACK_HOST_HEADER_HOSTS


class TestAllowedHostsExtension:
    """``ARXMCP_ALLOWED_HOSTS`` EXTENDS the loopback floor, never replaces it.

    Container/k8s deployments need this: liveness/readiness probes and the
    Prometheus scrape reach the server by pod IP or Service DNS name, not by
    loopback, so Threat-5 Host validation rejected every one of them with the
    loopback-only allow-list. The security property that must survive the
    escape hatch is that ONLY explicitly-listed hosts pass — a DNS-rebinding
    attacker's host is not on the list.
    """

    def test_empty_list_preserves_loopback_only_behavior(self):
        """The default. An empty extension must be byte-identical to the
        historical behavior, so shipping this feature changes nothing for
        every deployment that does not opt in."""
        assert _validate_host_header("127.0.0.1", allowed_port=None) is True
        assert _validate_host_header(
            "10.42.0.20", allowed_port=None, extra_hosts=frozenset()
        ) is False

    def test_listed_host_is_accepted(self):
        """The pod-IP case the k8s downward API feeds in."""
        assert _validate_host_header(
            "10.42.0.20", allowed_port=None, extra_hosts=frozenset({"10.42.0.20"})
        ) is True

    def test_unlisted_host_is_still_rejected(self):
        """The defense. Opting one host in does not open the door — this is
        what separates an allow-list from a disabled check."""
        assert _validate_host_header(
            "evil.com", allowed_port=None, extra_hosts=frozenset({"10.42.0.20"})
        ) is False
        assert _validate_host_header(
            "10.42.0.21", allowed_port=None, extra_hosts=frozenset({"10.42.0.20"})
        ) is False

    def test_loopback_floor_survives_a_populated_list(self):
        """The floor is a baseline, not a default that the var replaces.
        A deployment that lists only its pod IP must not lose localhost."""
        extra = frozenset({"10.42.0.20"})
        for host in ("127.0.0.1", "localhost", "[::1]", "testserver"):
            assert _validate_host_header(
                host, allowed_port=None, extra_hosts=extra
            ) is True

    def test_port_check_still_applies_to_an_extra_host(self):
        """The extension widens WHICH host is acceptable, not which port."""
        extra = frozenset({"10.42.0.20"})
        assert _validate_host_header(
            "10.42.0.20:7733", allowed_port=7733, extra_hosts=extra
        ) is True
        assert _validate_host_header(
            "10.42.0.20:8080", allowed_port=7733, extra_hosts=extra
        ) is False

    def test_service_dns_name_is_accepted_when_listed(self):
        """The other half of the k8s case — in-cluster Service DNS."""
        extra = frozenset({"arxmcp.arxmcp.svc.cluster.local"})
        assert _validate_host_header(
            "arxmcp.arxmcp.svc.cluster.local", allowed_port=None, extra_hosts=extra
        ) is True


class TestHostValidationMiddlewareExtraHosts:
    """The middleware's own normalization of ``extra_allowed_hosts``.

    ``_validate_host_header`` lowercases the incoming Host, so the configured
    list must be lowercased at construction or a ``Host`` header that differs
    only in case would be rejected against its own allow-list entry.
    """

    def test_configured_hosts_are_lowercased_and_stripped(self):
        mw = HostValidationMiddleware(
            app=None, extra_allowed_hosts=["  10.42.0.20 ", "ArXMCP.SVC.Cluster.Local"]
        )
        assert mw._extra_hosts == frozenset(
            {"10.42.0.20", "arxmcp.svc.cluster.local"}
        )

    def test_blank_entries_are_dropped(self):
        """A blank entry kept in the set would become an empty-string
        allow-list member, and a whitespace-only ``Host`` header normalizes to
        exactly that — so a stray comma in the env var would admit it.

        (A genuinely absent/empty Host header is a separate, deliberate pass
        at ``_validate_host_header``'s first branch — it never reaches the
        allow-list. This test is about the whitespace-only value that does.)
        """
        mw = HostValidationMiddleware(app=None, extra_allowed_hosts=["", "   "])
        assert mw._extra_hosts == frozenset()
        assert _validate_host_header(
            "   ", allowed_port=None, extra_hosts=mw._extra_hosts
        ) is False
        # Pin the hazard itself: had the blank survived, this would pass.
        assert _validate_host_header(
            "   ", allowed_port=None, extra_hosts=frozenset({""})
        ) is True

    def test_default_is_an_empty_frozenset(self):
        """Omitting the kwarg entirely is the loopback-only path."""
        mw = HostValidationMiddleware(app=None)
        assert mw._extra_hosts == frozenset()


# ===========================================================================
# F4 regression — pin upstream session-id generator identity
# ===========================================================================


class TestUpstreamSessionIdGenerator:
    """F4: the loose ``≥32 hex chars`` test would not catch a
    regression where upstream ``mcp`` swaps to a non-CSRNG generator
    (uuid1, MD5(time), monotonic counter). Pin the upstream source
    so a refactor that changes it fails THIS test rather than
    silently shipping weaker session ids."""

    def test_streamable_http_manager_uses_uuid4(self):
        """If upstream changes the session-id generator, this test
        fails loudly so we re-evaluate entropy guarantees."""
        import inspect

        import mcp.server.streamable_http_manager as mod

        src = inspect.getsource(mod)
        assert "uuid4()" in src, (
            "upstream mcp lib appears to have changed its session-id "
            "generator from uuid4(). Re-verify entropy guarantees and "
            "the deviation note in the implementation summary before "
            "updating this test. Source path: "
            f"{inspect.getfile(mod)}"
        )


# ===========================================================================
# F5 regression — log level default + DEBUG-no-body
# ===========================================================================


class TestLogLevelHardening:
    """Brief item 4: ``ARXMCP_LOG_LEVEL`` defaults to INFO; DEBUG-
    level logs must never emit chunk body content."""

    def test_log_level_default_is_info(self):
        """A future refactor that flips the default to DEBUG would
        regress brief item 4 (paper bodies in logs)."""
        cfg = Config()
        assert cfg.log_level == "INFO", (
            f"ARXMCP_LOG_LEVEL default must be INFO; got "
            f"{cfg.log_level!r}. DEBUG-level logs may emit chunk body "
            f"content; INFO is the safe default."
        )

    def test_debug_logs_do_not_emit_chunk_body_content(
        self, _seeded_lancedb, _mocked_bge, caplog
    ):
        """End-to-end check: load the corpus, run a search at DEBUG
        log level, assert no chunk body bytes appear in captured logs.

        The seeded corpus has chunks with ``body_text='chunk body 1'``
        and ``body_text='chunk body 2'``. We assert neither sentinel
        appears in any DEBUG log record. A regression here would mean
        a logger was inadvertently configured to dump body content."""
        import logging

        cfg = Config(lancedb_path=_seeded_lancedb)
        app = create_app(cfg)
        with caplog.at_level(logging.DEBUG), TestClient(app) as client:
            r = client.get("/healthz")
            assert r.status_code == 200
            r = client.get("/readyz")
            assert r.status_code == 200
        # Sentinel strings the seed corpus put in body_text.
        sentinels = ("chunk body 1", "chunk body 2")
        for record in caplog.records:
            msg = record.getMessage()
            for sentinel in sentinels:
                assert sentinel not in msg, (
                    f"DEBUG log emitted chunk body content "
                    f"({sentinel!r} in record from "
                    f"{record.name}:{record.levelname}). "
                    f"Brief item 4: DEBUG-level logs MUST never emit "
                    f"chunk body content."
                )


# ===========================================================================
# F6 regression — security event WARN logs on rejections
# ===========================================================================


class TestSecurityEventLogging:
    """F6: every reject path must emit a WARN log so ops can alert."""

    def test_origin_reject_emits_warn_log(self, warm_app, caplog):
        import logging

        with caplog.at_level(logging.WARNING, logger="server.middleware.security"):
            r = warm_app.get("/healthz", headers={"Origin": "https://evil.com"})
        assert r.status_code == 403
        msgs = [
            r.getMessage()
            for r in caplog.records
            if r.name == "server.middleware.security"
        ]
        assert any("origin rejected" in m for m in msgs), (
            f"expected 'origin rejected' WARN log; got {msgs}"
        )

    def test_host_reject_emits_warn_log(self, warm_app, caplog):
        import logging

        with caplog.at_level(logging.WARNING, logger="server.middleware.security"):
            r = warm_app.get("/healthz", headers={"Host": "attacker.example.com"})
        assert r.status_code == 421
        msgs = [
            r.getMessage()
            for r in caplog.records
            if r.name == "server.middleware.security"
        ]
        assert any("host rejected" in m for m in msgs), (
            f"expected 'host rejected' WARN log; got {msgs}"
        )

    def test_oversize_content_length_emits_warn_log(
        self, _seeded_lancedb, _mocked_bge, caplog
    ):
        import logging

        cfg = Config(lancedb_path=_seeded_lancedb)
        app = create_app(cfg)
        with (
            caplog.at_level(
                logging.WARNING, logger="server.middleware.security"
            ),
            TestClient(app) as client,
        ):
            r = client.post(
                "/healthz",
                content=b"x" * 100,
                headers={
                    "Content-Length": str(REQUEST_BODY_MAX_BYTES + 1),
                    "Content-Type": "application/octet-stream",
                },
            )
        assert r.status_code == 413
        msgs = [
            r.getMessage()
            for r in caplog.records
            if r.name == "server.middleware.security"
        ]
        assert any("content-length" in m for m in msgs), (
            f"expected 'content-length' WARN log; got {msgs}"
        )


# ===========================================================================
# F7 regression — middleware order pinned by test
# ===========================================================================


class TestMiddlewareOrder:
    """F7: the implementation summary claims OriginValidation runs
    BEFORE the request-body limit so an evil-origin POST is rejected
    without buffering its body. Without a test, a future refactor
    that flips ``add_middleware`` order silently inverts the property.
    """

    def test_evil_origin_with_oversize_body_returns_403_not_413(
        self, warm_app
    ):
        """Send an evil-origin POST with a Content-Length declaring a
        size over the cap. If Origin runs first (correct), we get 403.
        If body limit runs first (regression), we get 413."""
        r = warm_app.post(
            "/healthz",
            content=b"x" * 100,
            headers={
                "Origin": "https://evil.com",
                "Content-Length": str(REQUEST_BODY_MAX_BYTES + 1),
                "Content-Type": "application/octet-stream",
            },
        )
        assert r.status_code == 403, (
            f"middleware order regression — Origin must run before "
            f"body limit. Got status={r.status_code} body={r.text[:200]}"
        )


# ===========================================================================
# F8 regression — brief AC literal endpoint is /mcp
# ===========================================================================


class TestBriefAcLiteralEndpoint:
    """F8: the brief AC literally specifies ``/mcp`` as the test
    endpoint. Earlier tests probe ``/healthz`` because the middleware
    is universal — but a regression that mistakenly scopes the
    middleware to non-``/mcp`` paths would not be caught. Pin the
    /mcp path."""

    def test_evil_origin_on_mcp_returns_403(self, warm_app):
        """Brief AC #1 — literal endpoint."""
        r = warm_app.post(
            "/mcp/",
            json={"jsonrpc": "2.0", "id": 1, "method": "initialize"},
            headers={
                "Origin": "https://evil.com",
                "Accept": "application/json, text/event-stream",
                "Content-Type": "application/json",
                "Host": "127.0.0.1:7733",
            },
        )
        assert r.status_code == 403
        assert r.json()["error"] == "origin_forbidden"

    def test_no_origin_on_mcp_proceeds(self, warm_app):
        """Brief AC #2 — literal endpoint. Must not get 403 for the
        Origin reason."""
        r = warm_app.post(
            "/mcp/",
            json={
                "jsonrpc": "2.0",
                "id": 1,
                "method": "initialize",
                "params": {
                    "protocolVersion": "2025-06-18",
                    "capabilities": {},
                    "clientInfo": {"name": "test", "version": "1.0"},
                },
            },
            headers={
                "Accept": "application/json, text/event-stream",
                "Content-Type": "application/json",
                "Host": "127.0.0.1:7733",
            },
        )
        # Anything other than 403 means Origin validation didn't fire.
        # The actual MCP-layer status (200/202) depends on session
        # handshake, which is exercised in test_server_startup.py.
        assert r.status_code != 403, (
            f"no-Origin request to /mcp must not be 403; got "
            f"status={r.status_code} body={r.text[:200]}"
        )


# ===========================================================================
# F9 regression — userinfo on Origin → reject
# ===========================================================================


class TestOriginUserinfoRejected:
    """F9: a non-empty userinfo on an Origin header
    (``http://localhost@evil.com``) is anomalous and should be
    rejected even if the resolved host happens to be loopback."""

    def test_userinfo_in_origin_with_loopback_host_rejected(self, warm_app):
        # urlparse('http://localhost@127.0.0.1').hostname == '127.0.0.1'
        # but the userinfo 'localhost' is anomalous → reject.
        r = warm_app.get(
            "/healthz",
            headers={"Origin": "http://localhost@127.0.0.1"},
        )
        assert r.status_code == 403

    def test_userinfo_with_password_rejected(self, warm_app):
        r = warm_app.get(
            "/healthz",
            headers={"Origin": "http://user:pass@127.0.0.1"},
        )
        assert r.status_code == 403


# ===========================================================================
# F12 regression — case insensitivity pinned
# ===========================================================================


class TestOriginCaseInsensitive:
    """F12: ``urlparse`` lowercases scheme + hostname; pin the
    behavior with a parametrized test so a future swap to a manual
    parser cannot regress the case-insensitive guarantee."""

    @pytest.mark.parametrize("origin", [
        "HTTP://localhost",
        "http://LOCALHOST",
        "HTTP://127.0.0.1",
        "http://[::1]",
    ])
    def test_uppercase_variants_accepted(self, origin):
        assert _origin_is_allowed(origin) is True


# ===========================================================================
# F13 regression — origin truncation in error response
# ===========================================================================


class TestOriginTruncatedInResponse:
    """F13: attacker-supplied origins are truncated in the 403 body
    to prevent amplification-style probes."""

    def test_long_origin_truncated_in_response_body(self, warm_app):
        # Construct an origin > 256 chars. urlparse handles long
        # paths fine; we want a long total origin string.
        long_path = "/a" * 200  # 400 chars
        long_origin = f"https://evil.com{long_path}"
        assert len(long_origin) > MAX_ECHOED_ORIGIN_LEN
        r = warm_app.get("/healthz", headers={"Origin": long_origin})
        assert r.status_code == 403
        body = r.json()
        # The echoed origin is at most MAX_ECHOED_ORIGIN_LEN chars.
        assert len(body["origin"]) <= MAX_ECHOED_ORIGIN_LEN, (
            f"echoed origin not truncated: len={len(body['origin'])}, "
            f"cap={MAX_ECHOED_ORIGIN_LEN}"
        )


# Suppress unused-import warning for ``time`` (kept for future timing tests).
_ = time
