"""desktop-distribution-m8 real-model gate: the frozen bundle ships no model
weights, and the production encode/rerank chains still produce the committed
vectors.

Fast tests run in every ``make test``. The ``requires_bundled_model``-marked
tests load ~4.6 GB of real weights from the operator's HuggingFace cache and
boot the frozen child, so they are opt-in and run by ``make desktop-model-check``
(``DESKTOP_BUNDLED_MODEL_GATE=1`` makes any skip fail the session).

The golden fixture is regenerated by feeding its own ``inputs`` block to
``tools/desktop_model_probe.py``; the command is recorded in the fixture's
``_provenance``. Regenerate ONLY when a pinned model revision changes — a
vector mismatch otherwise means the weights that loaded are not the weights
intended, which is exactly what this gate exists to catch.
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
import os
import subprocess
import sys
import time
from dataclasses import replace
from pathlib import Path

import numpy as np
import pytest

from server.desktop_child import COMPONENT
from server.desktop_contract import Bound, encode_frame, generate_startup_token, parse_frame
from tests.test_desktop_child import (
    _golden_launch,
    _readline_with_timeout,
    _request,
    _seed_root,
    _stop_process,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
DRIVER_PATH = REPO_ROOT / "apps" / "desktop" / "pyinstaller" / "desktop_package.py"
MODEL_PROBE = REPO_ROOT / "tools" / "desktop_model_probe.py"
GOLDEN = REPO_ROOT / "tests" / "fixtures" / "desktop_model" / "golden_v1.json"

#: BGE-M3's output width; a fixture of the wrong shape is a regenerated-wrong
#: fixture, not a tolerance question.
EMBEDDING_DIM = 1024

#: Element-wise tolerance for both the 1024-dim vectors and the rerank scores.
#: MEASURED, not guessed: four consecutive probe runs on this host — spanning
#: OMP_NUM_THREADS 2/3/4 and both offline and online hub resolution — differed
#: by exactly 0.0 in every element and every score. 1e-6 is therefore pure
#: headroom (~4e-6 of the largest observed element, 0.252) for float32 CPU
#: reduction-order differences on another arm64 host, NOT a margin sized to
#: make a drifting assertion pass. Loosening it needs a re-measurement here.
TOLERANCE = 1e-6

#: Filename shapes that would mean model weights shipped inside the bundle.
WEIGHT_SUFFIXES = (".safetensors", ".ckpt", ".pt", ".pth", ".gguf", ".onnx", ".h5")


def _driver():
    spec = importlib.util.spec_from_file_location("arxmcp_desktop_package", DRIVER_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _golden() -> dict:
    return json.loads(GOLDEN.read_text(encoding="utf-8"))


def _probe_env(tmp_path: Path) -> dict[str, str]:
    """Explicit launch environment for a real-model subprocess.

    Never inherits the runner's: ``tests/conftest.py`` sets
    ``KMP_DUPLICATE_LIB_OK`` session-wide and the desktop launch contract
    forbids it (AC3). ``HOME`` is the real one because that is where the
    EXTERNAL HuggingFace cache lives; the offline flags prove the run resolves
    the pinned revisions from that cache rather than downloading them.
    """
    env = {
        "PATH": "/usr/bin:/bin",
        "HOME": str(Path.home()),
        "TMPDIR": str(tmp_path),
        "LANG": "en_US.UTF-8",
        "HF_HUB_OFFLINE": "1",
        "TRANSFORMERS_OFFLINE": "1",
        "TOKENIZERS_PARALLELISM": "false",
    }
    if "HF_HOME" in os.environ:
        env["HF_HOME"] = os.environ["HF_HOME"]
    return env


# --- fast tests (every `make test`) ---


def test_model_probe_rejects_a_forbidden_launch_environment():
    """AC3: the process that does the compute refuses to start with
    KMP_DUPLICATE_LIB_OK set, so the golden vectors can never be produced
    under the suppression flag the desktop contract forbids."""
    spec = importlib.util.spec_from_file_location("arxmcp_model_probe", MODEL_PROBE)
    probe = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(probe)
    assert "KMP_DUPLICATE_LIB_OK" in probe.FORBIDDEN_ENV
    probe.validate_environment({"PATH": "/usr/bin"})
    for hostile in ({"KMP_DUPLICATE_LIB_OK": "TRUE"}, {"DYLD_INSERT_LIBRARIES": "/x"}):
        with pytest.raises(RuntimeError, match="forbidden environment"):
            probe.validate_environment(hostile)


def test_golden_fixture_matches_the_live_model_pins():
    """A revision bump with a stale golden would compare new weights against
    old vectors and read as a corruption; pin the fixture to the constants."""
    from ingest.embedder import BGE_M3_COMMIT_SHA
    from server.retrieval.rerank import BGE_RERANKER_COMMIT_SHA, RERANKER_MODEL_ID

    golden = _golden()
    assert golden["embedder_revision"] == BGE_M3_COMMIT_SHA
    assert golden["reranker_revision"] == BGE_RERANKER_COMMIT_SHA
    assert golden["reranker_id"] == RERANKER_MODEL_ID


def test_golden_fixture_is_wellformed_and_discriminating():
    """The fixture must be able to FAIL: L2-normalized 1024-dim vectors, and a
    rerank ordering that separates the on-topic body from the off-topic ones by
    orders of magnitude, so a mis-loaded model cannot coincidentally match."""
    golden = _golden()
    inputs = golden["inputs"]
    assert set(golden["vectors"]) == set(inputs["queries"])
    for query, vector in golden["vectors"].items():
        array = np.asarray(vector, dtype=np.float32)
        assert array.shape == (EMBEDDING_DIM,), query
        assert abs(float(np.linalg.norm(array)) - 1.0) < 1e-5, query
    scores = [row["score"] for row in golden["rerank_scores"]]
    assert scores[0] > 0.5
    assert max(scores[1:]) < 0.01


# --- the model gate (requires_bundled_model; `make desktop-model-check`) ---


@pytest.fixture(scope="module")
def bundle() -> Path:
    """The frozen bundle built by ``make desktop-package``. Absence RAISES:
    under the gate env a skip fails the session anyway (m6/m7 precedent)."""
    dp = _driver()
    path = dp.DEFAULT_ROOT / "dist" / dp.BUNDLE_NAME
    if not (path / dp.CHILD_EXE).is_file():
        raise RuntimeError(
            f"no frozen bundle at {path}; run `make desktop-package` first "
            "(`make desktop-model-check` does this for you)"
        )
    return path


@pytest.mark.requires_bundled_model
def test_bundle_carries_no_model_weights(bundle: Path):
    """AC5: the read-only application bundle ships code, never weights — the
    ~4.6 GB of BGE-M3 + reranker tensors stay in the operator's HF cache."""
    weights: list[str] = []
    hf_cache_dirs: list[str] = []
    files_walked = 0
    for path in bundle.rglob("*"):
        rel = path.relative_to(bundle).as_posix()
        if path.is_dir():
            if path.name.startswith("models--") or path.name == "blobs":
                hf_cache_dirs.append(rel)
            continue
        files_walked += 1
        if path.suffix in WEIGHT_SUFFIXES or path.name.startswith("pytorch_model"):
            weights.append(rel)
    assert weights == [], f"model weight files shipped in the bundle: {weights}"
    assert hf_cache_dirs == [], f"HF cache tree shipped in the bundle: {hf_cache_dirs}"
    # Tripwire: a walk that found nothing cannot distinguish clean from broken.
    assert files_walked >= 4000, f"bundle walk covered only {files_walked} files"


@pytest.mark.requires_bundled_model
def test_hf_cache_resolves_outside_the_bundle(bundle: Path):
    """AC4's external-cache half: both pinned snapshots exist, and the cache
    root they live under is not reachable from inside the bundle."""
    from ingest.embedder import BGE_M3_COMMIT_SHA
    from server.model_loader import _huggingface_cache_root
    from server.retrieval.rerank import BGE_RERANKER_COMMIT_SHA, RERANKER_MODEL_ID

    cache_root = _huggingface_cache_root().resolve()
    assert not cache_root.is_relative_to(bundle.resolve())
    for model_id, revision in (
        ("BAAI/bge-m3", BGE_M3_COMMIT_SHA),
        (RERANKER_MODEL_ID, BGE_RERANKER_COMMIT_SHA),
    ):
        safe = "models--" + model_id.replace("/", "--")
        snapshot = cache_root / safe / "snapshots" / revision
        assert snapshot.is_dir(), f"{model_id}@{revision} is not cached at {snapshot}"


@pytest.mark.requires_bundled_model
def test_real_models_reproduce_the_golden_vectors(tmp_path):
    """AC4: encoding the fixed input set through the PRODUCTION chains
    reproduces the committed vectors and rerank scores. Loading weights proves
    the files parsed; only comparing output proves they are the right ones."""
    golden = _golden()
    proc = subprocess.run(
        [sys.executable, str(MODEL_PROBE)],
        input=json.dumps(golden["inputs"]),
        capture_output=True,
        text=True,
        env=_probe_env(tmp_path),
        cwd=str(REPO_ROOT),
        timeout=900,
    )
    assert proc.returncode == 0, f"model probe failed: {proc.stderr[-3000:]}"
    observed = json.loads(proc.stdout)

    assert observed["embedder_revision"] == golden["embedder_revision"]
    assert observed["reranker_revision"] == golden["reranker_revision"]
    assert not Path(observed["hf_cache_root"]).is_relative_to(REPO_ROOT)

    for query, expected in golden["vectors"].items():
        delta = np.abs(
            np.asarray(observed["vectors"][query], dtype=np.float32)
            - np.asarray(expected, dtype=np.float32)
        ).max()
        assert delta <= TOLERANCE, f"{query!r} drifted by {delta:g} (> {TOLERANCE:g})"
    for expected_row, observed_row in zip(
        golden["rerank_scores"], observed["rerank_scores"], strict=True
    ):
        assert observed_row["body"] == expected_row["body"]
        drift = abs(observed_row["score"] - expected_row["score"])
        assert drift <= TOLERANCE, f"rerank score drifted by {drift:g}"


@pytest.mark.requires_bundled_model
def test_frozen_child_warms_every_model_from_the_external_cache(bundle, tmp_path):
    """AC4's boot half + AC3 on the heaviest real path: the FROZEN child
    handshakes, loads BGE-M3, LanceDB and the reranker with no
    KMP_DUPLICATE_LIB_OK in its environment, and reports an all-true warm map.
    Its identity is the executable's own bytes (m7 H2), so the launch frame
    must carry the FROZEN digest, not this checkout's module digest."""
    dp = _driver()
    exe = bundle / dp.CHILD_EXE
    root = _seed_root(tmp_path / "runtime")
    token = generate_startup_token()
    launch = replace(
        _golden_launch(),
        data_root=root.as_posix(),
        executable=replace(
            _golden_launch().executable,
            component=COMPONENT,
            sha256=hashlib.sha256(exe.read_bytes()).hexdigest(),
            version=_frozen_version(bundle),
        ),
        log_location=(root / "logs" / "desktop-child.log").as_posix(),
        startup_token=token,
    )
    env = _probe_env(tmp_path)
    env["ARXMCP_ENABLE_RERANK"] = "1"
    assert "KMP_DUPLICATE_LIB_OK" not in env, "AC3: the launch env must not carry it"
    log_handle = (root / "logs" / "desktop-child.log").open("wb")
    process = subprocess.Popen(
        [str(exe)],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=log_handle,
        env=env,
    )
    try:
        process.stdin.write(encode_frame(launch))
        process.stdin.flush()
        bound = parse_frame(_readline_with_timeout(process.stdout, timeout=600.0))
        assert isinstance(bound, Bound), bound
        deadline = time.monotonic() + 120.0
        while True:
            status, _, body = _request(bound.endpoint.port, "/readyz", token=token.expose())
            if status == 200 or time.monotonic() >= deadline:
                break
            time.sleep(2.0)
        assert status == 200, body[:400]
        assert json.loads(body)["warm"] == {
            "embedder": True,
            "lancedb": True,
            "reranker": True,
        }
    finally:
        _stop_process(process)
        log_handle.close()


def _frozen_version(bundle: Path) -> str:
    """The wheel version baked into the bundle, read the way the frozen child's
    ``importlib.metadata`` lookup resolves it."""
    dist_infos = sorted(bundle.glob("_internal/arxmcp-*.dist-info"))
    if len(dist_infos) != 1:
        raise RuntimeError(f"expected one arxmcp dist-info in {bundle}, got {dist_infos}")
    # ``.dist-info`` carries its own hyphen, so split the suffix off first.
    return dist_infos[0].name.removesuffix(".dist-info").split("-", 1)[1]
