"""desktop-distribution-m7 packaging gate: PyInstaller bundle hygiene, plus
m8's OpenMP consolidation (exactly one runtime; a restored second copy aborts).

Fast tests run in every ``make test``. The ``requires_desktop_package``-marked
tests are the authoritative AC1-AC5 evidence: they provision the hash-pinned
build venv, run TWO independent ~74 s PyInstaller builds, and assert against
the real frozen artifact — never a mock (the hollow-mock precedent this file
must not repeat is ``test_desktop_sidecar_spike.py::test_probe_calls_freeze_support``,
which proves a monkeypatched ``freeze_support`` was called, not that the
frozen re-exec guard works). Run them via ``make desktop-package-check``,
whose ``DESKTOP_PACKAGE_GATE=1`` makes any skip fail the session.
"""

from __future__ import annotations

import ast
import hashlib
import importlib.util
import json
import os
import shutil
import signal
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
DRIVER_PATH = REPO_ROOT / "apps" / "desktop" / "pyinstaller" / "desktop_package.py"
DESKTOP_CHILD = REPO_ROOT / "server" / "desktop_child.py"

#: AC1's pinned exception-set size, mirrored here so widening the set needs an
#: edit in BOTH files (EXPECTED_TOOL_SCHEMA_SHA256 re-pin discipline). The set
#: was MEASURED EMPTY: two independent 2026-08-09 builds diffed to zero paths
#: once the spec sorted the two observed ordering drifts (base_library.zip
#: members, PYZ TOC); rationale lives beside the driver's frozenset.
PINNED_EXCEPTION_COUNT = 0
PINNED_EXCEPTIONS: frozenset[str] = frozenset()

#: AC2 LaTeX fixtures reused from tests/test_equation_latex_route.py — real
#: query-path inputs, converted independently in the source venv AND inside
#: the frozen bundle within the same test invocation (never a checked-in
#: golden generated by the bundle itself).
LATEX_FIXTURES = [
    r"\int_a^b g(t) dt",
    r"\sum_{n=0}^\infty a_n",
    r"\int_0^1 f(x)dx",
    r"\frac{a}{b}",
    r"\mathbb{C}",
    "x+y",
]

_driver_cache = None


def _driver():
    global _driver_cache
    if _driver_cache is None:
        spec = importlib.util.spec_from_file_location(
            "arxmcp_desktop_package", DRIVER_PATH
        )
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        _driver_cache = module
    return _driver_cache


def _frozen_env(tmp_path: Path) -> dict[str, str]:
    """Explicit minimal env for frozen-executable launches: never inherit the
    test runner's environment (conftest sets KMP_DUPLICATE_LIB_OK session-wide,
    which the desktop launch contract forbids)."""
    home = tmp_path / "home"
    tmpdir = tmp_path / "tmp"
    home.mkdir(parents=True, exist_ok=True)
    tmpdir.mkdir(parents=True, exist_ok=True)
    return {
        "PATH": "/usr/bin:/bin",
        "HOME": str(home),
        "TMPDIR": str(tmpdir),
        "LANG": "en_US.UTF-8",
    }


# --- fast tests (every `make test`) ---


def test_freeze_support_is_first_statement_of_main_guard():
    """AC3 static half: the guard's FIRST statement is freeze_support(), so a
    frozen spawn child is intercepted before main() touches the control stream."""
    tree = ast.parse(DESKTOP_CHILD.read_text(encoding="utf-8"))
    guards = [
        node
        for node in tree.body
        if isinstance(node, ast.If)
        and isinstance(node.test, ast.Compare)
        and isinstance(node.test.left, ast.Name)
        and node.test.left.id == "__name__"
    ]
    assert len(guards) == 1, "expected exactly one __main__ guard"
    first = guards[0].body[0]
    assert isinstance(first, ast.Expr) and isinstance(first.value, ast.Call)
    call = first.value.func
    assert isinstance(call, ast.Attribute) and call.attr == "freeze_support"
    assert isinstance(call.value, ast.Name) and call.value.id == "multiprocessing"


def test_exception_set_is_closed_and_size_pinned():
    """AC1's tripwire: the nondeterminism exception set is a frozenset whose
    exact size AND membership are pinned in two files; silent growth fails."""
    dp = _driver()
    assert isinstance(dp.NONDETERMINISTIC_EXCEPTIONS, frozenset)
    assert dp.EXPECTED_EXCEPTION_COUNT == PINNED_EXCEPTION_COUNT
    assert len(dp.NONDETERMINISTIC_EXCEPTIONS) == PINNED_EXCEPTION_COUNT
    assert dp.NONDETERMINISTIC_EXCEPTIONS == PINNED_EXCEPTIONS


def test_default_needles_cover_raw_and_realpath_temp_root(tmp_path):
    """H3 guard: on macOS ``TMPDIR`` (``/var/folders/...``) and its realpath
    (``/private/var/...``) differ, and the toolchain embeds the RAW form the
    build was handed. Searching only the realpath matched nothing at all."""
    import os
    import tempfile

    dp = _driver()
    raw = tempfile.gettempdir()
    real = os.path.realpath(raw)
    needles = dp.default_needles()
    assert needles["tmp"] == raw.encode()
    if real != raw:
        assert needles["tmp_real"] == real.encode()
    # The planted needle the pre-fix scanner could not see.
    (tmp_path / "planted.pyc").write_bytes(b"\x00" * 16 + f"{raw}/x.py".encode())
    assert dp.scan_tree(tmp_path, needles)["hits"] == {"planted.pyc": ["tmp"]}


def test_default_needles_add_uncovered_build_paths(tmp_path):
    """M9/L1 guard: a checkout outside ``$HOME`` leaves the build directory —
    the most likely leaked prefix — unscanned unless it is its own needle."""
    dp = _driver()
    outside = Path("/opt/build/arxmcp-checkout")
    needles = dp.default_needles(build_paths=(outside,))
    added = [label for label in needles if label.startswith("build_path_")]
    assert added, "an out-of-$HOME build root must contribute a needle"
    (tmp_path / "leaky.bin").write_bytes(b"\x00" + str(outside).encode())
    assert "leaky.bin" in dp.scan_tree(tmp_path, needles)["hits"]
    # A path already covered by $HOME contributes nothing new.
    assert dp.default_needles(build_paths=(Path.home() / "x",)) == dp.default_needles()


def test_build_once_fails_closed_on_vacuous_scan_coverage():
    """M5 guard: an archive reader yielding an empty TOC must be
    distinguishable from a genuinely clean bundle."""
    dp = _driver()
    with pytest.raises(dp.BuildError, match="zero files"):
        dp._require_scan_coverage({"files_scanned": 0, "embedded": {}})
    with pytest.raises(dp.BuildError, match="no .pyc entries"):
        dp._require_scan_coverage(
            {
                "files_scanned": 10,
                "embedded": {"entries_scanned": 0, "pyc_entries": 0},
            }
        )
    dp._require_scan_coverage(
        {"files_scanned": 10, "embedded": {"entries_scanned": 5, "pyc_entries": 5}}
    )


def test_verify_cli_exit_codes(monkeypatch, tmp_path):
    """M1 guard: the ``verify`` subcommand duplicates the gate's assertions in
    code no make target runs; both failure exits must be real."""
    dp = _driver()

    def _report(differing, hits, libomp):
        return {
            "determinism": {"differing": differing},
            "scan": {"hits": hits},
            "libomp": {"regular": libomp, "symlinks": {}},
        }

    cases = [
        (([], {}, [{"path": "torch/lib/libomp.dylib"}]), 0),
        ((["lib/x.so"], {}, [{"path": "torch/lib/libomp.dylib"}]), 1),
        (([], {"lib/x.so": ["home"]}, [{"path": "torch/lib/libomp.dylib"}]), 1),
        # m8: a second OpenMP copy must exit non-zero on this path too.
        (([], {}, [{"path": "a/libomp.dylib"}, {"path": "b/libomp.dylib"}]), 1),
    ]
    for (differing, hits, libomp), expected in cases:
        monkeypatch.setattr(
            dp,
            "verify_determinism",
            lambda root, d=differing, h=hits, lo=libomp: _report(d, h, lo),
        )
        assert dp.main(["verify", "--root", str(tmp_path)]) == expected


def test_scanner_finds_needle_in_binary_and_extensionless_files(tmp_path):
    dp = _driver()
    needles = {"home": b"/Users/buildbot-home"}
    (tmp_path / "clean.dylib").write_bytes(os.urandom(64) + b"\x00clean\x00")
    (tmp_path / "leaky.pyc").write_bytes(b"\x00" * 32 + b"/Users/buildbot-home/x.py\x00")
    (tmp_path / "no-extension").write_bytes(b"prefix /Users/buildbot-home tail")
    report = dp.scan_tree(tmp_path, needles)
    assert set(report["hits"]) == {"leaky.pyc", "no-extension"}
    assert report["files_scanned"] == 3
    assert report["bytes_scanned"] == report["lstat_bytes"]


def test_scanner_reads_nested_zip_members(tmp_path):
    """A raw byte grep cannot see inside deflated members; the scanner must."""
    import zipfile

    dp = _driver()
    archive = tmp_path / "base_library.zip"
    with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("mod.pyc", b"A" * 512 + b"/Users/buildbot-home/mod.py" + b"B" * 512)
    report = dp.scan_tree(tmp_path, {"home": b"/Users/buildbot-home"})
    hits = report["hits"]["base_library.zip"]
    assert any(entry.startswith("zip:mod.pyc") for entry in hits)
    assert report["zip_pyc_members"] == 1


def test_scanner_needle_split_across_chunk_boundary(tmp_path):
    dp = _driver()
    needle = b"/Users/buildbot-home"
    blob = b"\x00" * (4 * 1024 * 1024 - 10) + needle + b"\x00" * 64
    (tmp_path / "big.bin").write_bytes(blob)
    report = dp.scan_tree(tmp_path, {"home": needle})
    assert "big.bin" in report["hits"]


def test_sanitizer_removes_direct_url_and_reports_leak(tmp_path):
    dp = _driver()
    dist_info = tmp_path / "arxmcp-0.1.0.dist-info"
    dist_info.mkdir(parents=True)
    (dist_info / "direct_url.json").write_text(
        json.dumps({"url": "file:///tmp/arxmcp-wheel-check/arxmcp.whl"}),
        encoding="utf-8",
    )
    report = dp.sanitize_direct_url(tmp_path)
    assert report["found"] is True
    assert report["leak_observed"] is True
    assert not (dist_info / "direct_url.json").exists()
    again = dp.sanitize_direct_url(tmp_path)
    assert again["found"] is False


def test_libomp_exclusion_predicate_targets_only_the_redundant_copy():
    """m8 AC1's sharpest failure mode: a string-match bug here drops the LIVE
    OpenMP runtime instead of the orphan and the bundle dies at first FAISS
    import. The predicate must match faiss's private copy and nothing else."""
    dp = _driver()
    assert dp.is_duplicate_libomp("faiss/.dylibs/libomp.dylib")
    assert dp.is_duplicate_libomp("faiss\\.dylibs\\libomp.dylib")
    for spared in ("torch/lib/libomp.dylib", "libomp.dylib", "faiss/_swigfaiss.abi3.so"):
        assert not dp.is_duplicate_libomp(spared), spared
    assert dp.is_canonical_libomp("torch/lib/libomp.dylib")
    assert not dp.is_canonical_libomp("faiss/.dylibs/libomp.dylib")


def test_libomp_inventory_counts_files_not_names(tmp_path):
    """A symlink adds a NAME, not a mapped image, so it must not read as a
    second copy — the shipped bundle deliberately carries one of each."""
    dp = _driver()
    (tmp_path / "torch" / "lib").mkdir(parents=True)
    (tmp_path / "torch" / "lib" / "libomp.dylib").write_bytes(b"canonical")
    os.symlink("torch/lib/libomp.dylib", tmp_path / "libomp.dylib")
    inventory = dp.libomp_inventory(tmp_path)
    assert [entry["path"] for entry in inventory["regular"]] == ["torch/lib/libomp.dylib"]
    assert inventory["symlinks"] == {"libomp.dylib": "torch/lib/libomp.dylib"}
    dp._require_single_libomp(inventory)

    (tmp_path / "faiss" / ".dylibs").mkdir(parents=True)
    (tmp_path / "faiss" / ".dylibs" / "libomp.dylib").write_bytes(b"orphan")
    two = dp.libomp_inventory(tmp_path)
    assert len(two["regular"]) == 2
    with pytest.raises(dp.BuildError, match="exactly one OpenMP runtime"):
        dp._require_single_libomp(two)


def test_libomp_pattern_covers_the_openmp_runtime_family():
    """A versioned or Intel-flavoured copy is the same hazard under a
    different filename; a literal ``libomp.dylib`` check would miss it."""
    dp = _driver()
    for name in ("libomp.dylib", "libomp.5.dylib", "libiomp5.dylib", "libgomp.so.1"):
        assert dp.LIBOMP_PATTERN.match(name), name
    for name in ("libompressed.dylib", "libcompression.dylib", "omp.dylib"):
        assert not dp.LIBOMP_PATTERN.match(name), name


def test_probe_and_driver_agree_on_the_openmp_filename_pattern():
    """The frozen probe cannot import the driver, so the loaded-image count and
    the filesystem count are enforced by two copies of one regex. Pin them
    equal or the two halves of the m8 evidence can silently diverge."""
    dp = _driver()
    spec = importlib.util.spec_from_file_location(
        "arxmcp_probe_entry", DRIVER_PATH.parent / "probe_entry.py"
    )
    probe = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(probe)
    assert probe.LIBOMP_NAME.pattern == dp.LIBOMP_PATTERN.pattern
    assert probe.FORBIDDEN_ENV[0] == "KMP_DUPLICATE_LIB_OK"


def _manifest_pair(tmp_path):
    a, b = tmp_path / "a", tmp_path / "b"
    for root in (a, b):
        (root / "sub").mkdir(parents=True)
        (root / "same.txt").write_text("same", encoding="utf-8")
        (root / "sub" / "content.bin").write_bytes(b"one")
    (b / "sub" / "content.bin").write_bytes(b"two")
    (b / "only-in-b").write_text("x", encoding="utf-8")
    return a, b


def test_manifest_diff_catches_content_and_membership(tmp_path):
    dp = _driver()
    a, b = _manifest_pair(tmp_path)
    diff = dp.manifest_diff(dp.file_manifest(a), dp.file_manifest(b))
    assert diff == ["only-in-b", "sub/content.bin"]


@pytest.mark.skipif(
    sys.platform == "win32", reason="POSIX mode bits: chmod only toggles read-only"
)
def test_manifest_diff_catches_mode(tmp_path):
    dp = _driver()
    a, b = _manifest_pair(tmp_path)
    (a / "mode.sh").write_text("#!/bin/sh\n", encoding="utf-8")
    (b / "mode.sh").write_text("#!/bin/sh\n", encoding="utf-8")
    (b / "mode.sh").chmod(0o755)
    diff = dp.manifest_diff(dp.file_manifest(a), dp.file_manifest(b))
    assert diff == ["mode.sh", "only-in-b", "sub/content.bin"]


# --- the packaging gate (requires_desktop_package; `make desktop-package-check`) ---


@pytest.fixture(scope="module")
def packaged():
    """Provision + TWO independent builds; module-scoped so every gate test
    asserts against the same evidence run. Prerequisite failures RAISE — under
    DESKTOP_PACKAGE_GATE a skip would fail the session anyway (m6 precedent)."""
    if shutil.which("uv") is None:
        raise RuntimeError(
            "uv is required for the desktop packaging gate; install uv and re-run "
            "`make desktop-package-check`"
        )
    dp = _driver()
    report = dp.verify_determinism(dp.DEFAULT_ROOT)
    return dp, report


@pytest.mark.requires_desktop_package
def test_two_builds_are_byte_identical_within_pinned_exceptions(packaged):
    """AC1: two independent PyInstaller invocations from the same tree, fresh
    work/dist paths each, per-file manifests diffed against the CLOSED set."""
    dp, report = packaged
    det = report["determinism"]
    assert det["manifest_entries"] >= 4000, "suspiciously small bundle manifest"
    # H1: without distinct, cold PYINSTALLER_CONFIG_DIRs the second build
    # copies its native binaries out of the first build's bincache, so an
    # empty exception set would be a cache replay rather than a reproduction.
    assert det["config_dirs_distinct"] is True
    assert det["config_dirs"][0] != det["config_dirs"][1]
    assert det["config_dir_b_cold"] is True
    unexpected = set(det["differing"]) - dp.NONDETERMINISTIC_EXCEPTIONS
    assert not unexpected, (
        f"NEW nondeterministic paths (grow the pinned set only with a per-entry "
        f"'why unavoidable' rationale): {sorted(unexpected)}"
    )


@pytest.mark.requires_desktop_package
def test_frozen_latex2mathml_output_matches_source_tree(packaged, tmp_path):
    """AC2: the bundled probe converts the SAME fixtures the source tree
    converts in this very process; outputs must be byte-identical, and the
    bundled symbol table must hash-match the source venv's copy."""
    import latex2mathml.converter as converter_mod

    dp, report = packaged
    bundle = Path(report["bundle"])
    proc = subprocess.run(
        [str(bundle / dp.PROBE_EXE)],
        input=json.dumps({"latex": LATEX_FIXTURES}),
        capture_output=True,
        text=True,
        env=_frozen_env(tmp_path),
        timeout=180,
    )
    assert proc.returncode == 0, f"probe failed: {proc.stderr[-2000:]}"
    frozen = json.loads(proc.stdout)
    for latex in LATEX_FIXTURES:
        expected = converter_mod.convert(latex)
        assert frozen["conversions"][latex].encode() == expected.encode(), (
            f"frozen conversion diverged for {latex!r}"
        )
    source_table = (
        Path(converter_mod.__file__).resolve().parent / "unimathsymbols.txt"
    )
    assert (
        frozen["symbol_table_sha256"]
        == hashlib.sha256(source_table.read_bytes()).hexdigest()
    )
    assert frozen["symbol_table_bytes"] == source_table.stat().st_size


#: Signals main() emits on ANY entry path, so the AC3 discriminator survives
#: changes to how main() fails. Deliberately NOT a traceback frame alone: the
#: pre-m7-rectify control arm asserted ``, in main`` only because the frozen
#: child crashed in ``executable_identity()``, which coupled the strongest AC3
#: evidence to a bug (M3). ``rejected launch`` is the clean-path marker; the
#: traceback frame is kept so an unexpected crash inside main() still counts
#: as having entered it.
_ENTERED_MAIN_MARKERS = (b"desktop child rejected launch", b", in main")


def _entered_main(stderr: bytes) -> bool:
    return any(marker in stderr for marker in _ENTERED_MAIN_MARKERS)


@pytest.mark.requires_desktop_package
def test_frozen_spawn_reexec_never_reenters_main(packaged, tmp_path):
    """AC3 dynamic half, on the REAL frozen executable — never a mocked
    freeze_support. main() ignores argv entirely, so absent freeze_support()
    a ``--multiprocessing-fork`` re-exec would behave exactly like the control
    arm: enter main() as a duplicate top-level desktop child. The control arm
    proves what entering main() looks like on this binary; the fork-flagged arm
    must never reach main() — freeze_support intercepts and multiprocessing's
    spawn_main dies on the unfed pipe with EOFError instead."""
    dp, report = packaged
    exe = str(Path(report["bundle"]) / dp.CHILD_EXE)
    env = _frozen_env(tmp_path)

    control = subprocess.run(
        [exe],
        stdin=subprocess.DEVNULL,
        capture_output=True,
        env=env,
        timeout=180,
    )
    assert control.returncode != 0
    assert _entered_main(control.stderr), (
        f"control arm never entered main(); stderr: {control.stderr[-2000:]}"
    )
    # H2: the frozen child must get PAST executable_identity() and reach the
    # launch-frame contract check — it used to die hashing a PYZ-internal
    # __file__, so the bundle could not complete a handshake at all.
    assert control.returncode == 2, (
        f"frozen child did not reach the launch-contract rejection (rc="
        f"{control.returncode}); stderr: {control.stderr[-2000:]}"
    )
    assert b"desktop child rejected launch" in control.stderr
    assert b"EOFError" not in control.stderr

    read_fd, write_fd = os.pipe()
    try:
        os.set_inheritable(read_fd, True)
        proc = subprocess.Popen(
            [exe, "--multiprocessing-fork", f"pipe_handle={read_fd}"],
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            env=env,
            pass_fds=(read_fd,),
        )
    finally:
        os.close(read_fd)
    os.close(write_fd)  # child's pipe read hits EOF; spawn_main dies unfed
    _, stderr = proc.communicate(timeout=180)
    assert not _entered_main(stderr), (
        f"fork re-exec fell through to main() — duplicate top-level process; "
        f"stderr: {stderr[-2000:]}"
    )
    assert b"EOFError" in stderr, (
        f"expected multiprocessing spawn_main to engage and hit pipe EOF; "
        f"stderr: {stderr[-2000:]}"
    )


@pytest.mark.requires_desktop_package
def test_no_direct_url_leak_in_bundle(packaged):
    """AC4: the leak must be OBSERVED pre-sanitize on the real toolchain path
    (a check that passes because the file never existed proves nothing), and
    the frozen tree must carry no file:// build-machine URL."""
    dp, report = packaged
    assert report["direct_url"]["leak_observed"] is True
    bundle = Path(report["bundle"])
    stray = list(bundle.rglob("direct_url.json"))
    assert stray == [], f"direct_url.json shipped in the bundle: {stray}"


@pytest.mark.requires_desktop_package
def test_bundle_carries_no_build_machine_paths(packaged):
    """AC5: zero occurrences of temp root / $HOME / username across ALL
    regular files — plus nested zips and the executables' embedded PYZ, where
    compiled .pyc bytes (co_filename) hide from a raw grep. Coverage floors +
    the bytes-read tripwire prove the scan actually opened everything."""
    _, report = packaged
    scan = report["scan"]
    assert scan["hits"] == {}
    assert scan["bytes_scanned"] == scan["lstat_bytes"]
    assert scan["files_scanned"] >= 4000
    assert scan["native_files"] >= 100
    assert scan["zip_pyc_members"] >= 100
    assert scan["embedded"]["pyc_entries"] >= 5000


@pytest.mark.requires_desktop_package
def test_bundle_ships_every_server_data_file_the_wheel_ships(packaged):
    """Derived, not enumerated: PyInstaller collects only ``.py``, so the
    wheel's ``server`` package-data was absent and ``create_app()`` died on the
    missing static directory — the frozen child could not boot at all. Compared
    against the build venv's installed tree so a new data file cannot drop out
    of the bundle the way it once dropped out of the wheel (CLAUDE.md §4.5b)."""
    dp, report = packaged
    installed = dp._site_packages(dp.build_venv_dir(dp.DEFAULT_ROOT)) / "server"
    expected = {
        path.relative_to(installed).as_posix()
        for path in installed.rglob("*")
        if path.is_file() and path.suffix not in {".py", ".pyc"}
    }
    assert expected, f"no server data files found under {installed}"
    frozen_root = Path(report["bundle"]) / "_internal" / "server"
    missing = sorted(rel for rel in expected if not (frozen_root / rel).is_file())
    assert missing == [], f"wheel data files absent from the bundle: {missing}"


def _run_omp_probe(bundle_dir: Path, dp, tmp_path: Path) -> subprocess.CompletedProcess:
    """Launch the OpenMP probe and return the completed process UNCHECKED.

    ``subprocess.run`` with no shell, so ``returncode`` is the CHILD's wait
    status: a SIGABRT surfaces as -6 here, where a shell pipeline would report
    its last stage instead and read as success.
    """
    return subprocess.run(
        [str(bundle_dir / dp.PROBE_EXE)],
        input=json.dumps({"mode": "omp"}),
        capture_output=True,
        text=True,
        env=_frozen_env(tmp_path),
        timeout=600,
    )


@pytest.mark.requires_desktop_package
def test_bundle_ships_exactly_one_openmp_runtime(packaged):
    """m8 AC1/AC2-A: MEASURED RED before the fix — the same scan reported two
    regular files, torch's canonical ``cc166d…`` and faiss's orphaned
    ``798920…``. The symlink is expected and is not a copy."""
    dp, report = packaged
    inventory = report["libomp"]
    dp._require_single_libomp(inventory)
    assert [entry["path"] for entry in inventory["regular"]] == [
        f"_internal/{dp.CANONICAL_LIBOMP}"
    ]
    assert inventory["symlinks"] == {"_internal/libomp.dylib": dp.CANONICAL_LIBOMP}
    assert not (Path(report["bundle"]) / "_internal" / dp.DUPLICATE_LIBOMP).exists()


@pytest.mark.requires_desktop_package
def test_frozen_faiss_and_torch_share_one_openmp_image(packaged, tmp_path):
    """m8 AC2-B AFTER arm + AC3: a real FAISS add+search followed by real
    multi-threaded Torch compute in ONE frozen process exits 0, with exactly
    one OpenMP image MAPPED — dyld's live image list, not a directory listing,
    because a copy that is present but never mapped is a different defect from
    a copy that is loaded. The probe refuses to start with
    KMP_DUPLICATE_LIB_OK set, so this cannot be a suppressed abort."""
    dp, report = packaged
    bundle = Path(report["bundle"])
    proc = _run_omp_probe(bundle, dp, tmp_path)
    assert proc.returncode == 0, f"omp probe failed: {proc.stderr[-3000:]}"
    result = json.loads(proc.stdout)
    assert result["faiss_neighbours"] == list(range(8))
    assert result["torch_checksum_finite"] is True
    assert result["torch_threads"] > 1, "a single-threaded run would not contend"
    if sys.platform == "darwin":
        assert result["openmp_images"] == [str(bundle / "_internal" / dp.CANONICAL_LIBOMP)]


@pytest.mark.requires_desktop_package
def test_a_second_openmp_copy_aborts_the_frozen_process(packaged, tmp_path):
    """m8 AC2-B BEFORE arm: prove the excluded copy is DANGEROUS, not merely
    redundant. Restoring faiss's upstream wheel state on a disposable clone —
    its private ``libomp.dylib`` (install name ``/DLC/faiss/.dylibs/…``) plus
    the fully-qualified load command PyInstaller rewrote to ``@rpath`` — makes
    dyld map a SECOND image and the process dies on ``OMP: Error #15``.

    That install name is the whole mechanism, and it is why merely re-adding
    the file (or ``dlopen``-ing it alongside) does not reproduce: PyInstaller
    rewrites BOTH copies' IDs to the same ``@rpath/libomp.dylib``, which dyld
    dedupes onto one image. The consolidation removes the accident.

    Mach-O only; the equivalent ELF injection is not the shipped artifact's
    failure mode (the m7 codesign test's platform-branch precedent).
    """
    if sys.platform != "darwin":
        return
    dp, report = packaged
    bundle = Path(report["bundle"])
    upstream = (
        dp._site_packages(dp.build_venv_dir(dp.DEFAULT_ROOT))
        / "faiss"
        / ".dylibs"
        / "libomp.dylib"
    )
    assert upstream.is_file(), f"upstream faiss OpenMP copy missing at {upstream}"

    clone = tmp_path / "fault-injected"
    shutil.copytree(bundle, clone, copy_function=os.link, symlinks=True)
    swig = clone / "_internal" / "faiss" / "_swigfaiss.abi3.so"
    # Break the hardlink BEFORE mutating: install_name_tool edits in place and
    # would otherwise rewrite the shipped artifact through the shared inode.
    payload = swig.read_bytes()
    swig.unlink()
    swig.write_bytes(payload)
    swig.chmod(0o755)
    orphan = clone / "_internal" / dp.DUPLICATE_LIBOMP
    orphan.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(upstream, orphan)
    for command in (
        ["/usr/bin/install_name_tool", "-change", "@rpath/libomp.dylib",
         "@loader_path/.dylibs/libomp.dylib", str(swig)],
        ["/usr/bin/codesign", "-f", "-s", "-", str(swig)],
    ):
        step = subprocess.run(command, capture_output=True, text=True, timeout=120)
        assert step.returncode == 0, f"{command[0]} failed: {step.stderr[-1000:]}"

    proc = _run_omp_probe(clone, dp, tmp_path / "faultenv")
    assert proc.returncode in (-signal.SIGABRT, 134), (
        f"the duplicate OpenMP copy did NOT abort the process (rc="
        f"{proc.returncode}); stdout={proc.stdout[-1000:]} "
        f"stderr={proc.stderr[-2000:]}"
    )
    assert "OMP: Error #15" in proc.stderr

    # The shipped artifact must be untouched by the injection.
    shipped = subprocess.run(
        ["/usr/bin/otool", "-L", str(bundle / "_internal" / "faiss" / "_swigfaiss.abi3.so")],
        capture_output=True,
        text=True,
        timeout=120,
    )
    assert "@rpath/libomp.dylib" in shipped.stdout
    assert "@loader_path/.dylibs/libomp.dylib" not in shipped.stdout


@pytest.mark.requires_desktop_package
def test_bundle_executables_exist_and_are_signed(packaged):
    """The artifact later signing work consumes: both executables present and
    carrying a valid (ad-hoc at this stage) macOS signature."""
    dp, report = packaged
    bundle = Path(report["bundle"])
    for name in (dp.CHILD_EXE, dp.PROBE_EXE):
        exe = bundle / name
        assert exe.is_file() and os.access(exe, os.X_OK)
    if sys.platform == "darwin":
        proc = subprocess.run(
            ["/usr/bin/codesign", "--verify", "--strict", str(bundle / dp.CHILD_EXE)],
            capture_output=True,
            text=True,
            timeout=120,
        )
        assert proc.returncode == 0, f"codesign verify failed: {proc.stderr}"
