"""desktop-distribution-m7 packaging gate: PyInstaller bundle hygiene.

Fast tests run in every ``make test``. The ``requires_desktop_package``-marked
tests are the authoritative AC1-AC5 evidence: they provision the hash-pinned
build venv, run TWO independent ~74 s PyInstaller builds, and assert against
the real frozen artifact — never a mock (the hollow-mock precedent this file
must not repeat is ``test_desktop_sidecar_spike.py::test_probe_calls_freeze_support``,
which proves a monkeypatched ``freeze_support`` was called, not that the
frozen re-exec guard works). Run them via ``make desktop-package-check``,
whose ``DESKTOP_PACKAGE_GATE=1`` makes any skip fail the session.
"""

from __future__ import annotations

import ast
import hashlib
import importlib.util
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
DRIVER_PATH = REPO_ROOT / "apps" / "desktop" / "pyinstaller" / "desktop_package.py"
DESKTOP_CHILD = REPO_ROOT / "server" / "desktop_child.py"

#: AC1's pinned exception-set size, mirrored here so widening the set needs an
#: edit in BOTH files (EXPECTED_TOOL_SCHEMA_SHA256 re-pin discipline). The set
#: was MEASURED EMPTY: two independent 2026-08-09 builds diffed to zero paths
#: once the spec sorted the two observed ordering drifts (base_library.zip
#: members, PYZ TOC); rationale lives beside the driver's frozenset.
PINNED_EXCEPTION_COUNT = 0
PINNED_EXCEPTIONS: frozenset[str] = frozenset()

#: AC2 LaTeX fixtures reused from tests/test_equation_latex_route.py — real
#: query-path inputs, converted independently in the source venv AND inside
#: the frozen bundle within the same test invocation (never a checked-in
#: golden generated by the bundle itself).
LATEX_FIXTURES = [
    r"\int_a^b g(t) dt",
    r"\sum_{n=0}^\infty a_n",
    r"\int_0^1 f(x)dx",
    r"\frac{a}{b}",
    r"\mathbb{C}",
    "x+y",
]

_driver_cache = None


def _driver():
    global _driver_cache
    if _driver_cache is None:
        spec = importlib.util.spec_from_file_location(
            "arxmcp_desktop_package", DRIVER_PATH
        )
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        _driver_cache = module
    return _driver_cache


def _frozen_env(tmp_path: Path) -> dict[str, str]:
    """Explicit minimal env for frozen-executable launches: never inherit the
    test runner's environment (conftest sets KMP_DUPLICATE_LIB_OK session-wide,
    which the desktop launch contract forbids)."""
    home = tmp_path / "home"
    tmpdir = tmp_path / "tmp"
    home.mkdir(parents=True, exist_ok=True)
    tmpdir.mkdir(parents=True, exist_ok=True)
    return {
        "PATH": "/usr/bin:/bin",
        "HOME": str(home),
        "TMPDIR": str(tmpdir),
        "LANG": "en_US.UTF-8",
    }


# --- fast tests (every `make test`) ---


def test_freeze_support_is_first_statement_of_main_guard():
    """AC3 static half: the guard's FIRST statement is freeze_support(), so a
    frozen spawn child is intercepted before main() touches the control stream."""
    tree = ast.parse(DESKTOP_CHILD.read_text(encoding="utf-8"))
    guards = [
        node
        for node in tree.body
        if isinstance(node, ast.If)
        and isinstance(node.test, ast.Compare)
        and isinstance(node.test.left, ast.Name)
        and node.test.left.id == "__name__"
    ]
    assert len(guards) == 1, "expected exactly one __main__ guard"
    first = guards[0].body[0]
    assert isinstance(first, ast.Expr) and isinstance(first.value, ast.Call)
    call = first.value.func
    assert isinstance(call, ast.Attribute) and call.attr == "freeze_support"
    assert isinstance(call.value, ast.Name) and call.value.id == "multiprocessing"


def test_exception_set_is_closed_and_size_pinned():
    """AC1's tripwire: the nondeterminism exception set is a frozenset whose
    exact size AND membership are pinned in two files; silent growth fails."""
    dp = _driver()
    assert isinstance(dp.NONDETERMINISTIC_EXCEPTIONS, frozenset)
    assert dp.EXPECTED_EXCEPTION_COUNT == PINNED_EXCEPTION_COUNT
    assert len(dp.NONDETERMINISTIC_EXCEPTIONS) == PINNED_EXCEPTION_COUNT
    assert dp.NONDETERMINISTIC_EXCEPTIONS == PINNED_EXCEPTIONS


def test_scanner_finds_needle_in_binary_and_extensionless_files(tmp_path):
    dp = _driver()
    needles = {"home": b"/Users/buildbot-home"}
    (tmp_path / "clean.dylib").write_bytes(os.urandom(64) + b"\x00clean\x00")
    (tmp_path / "leaky.pyc").write_bytes(b"\x00" * 32 + b"/Users/buildbot-home/x.py\x00")
    (tmp_path / "no-extension").write_bytes(b"prefix /Users/buildbot-home tail")
    report = dp.scan_tree(tmp_path, needles)
    assert set(report["hits"]) == {"leaky.pyc", "no-extension"}
    assert report["files_scanned"] == 3
    assert report["bytes_scanned"] == report["lstat_bytes"]


def test_scanner_reads_nested_zip_members(tmp_path):
    """A raw byte grep cannot see inside deflated members; the scanner must."""
    import zipfile

    dp = _driver()
    archive = tmp_path / "base_library.zip"
    with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("mod.pyc", b"A" * 512 + b"/Users/buildbot-home/mod.py" + b"B" * 512)
    report = dp.scan_tree(tmp_path, {"home": b"/Users/buildbot-home"})
    hits = report["hits"]["base_library.zip"]
    assert any(entry.startswith("zip:mod.pyc") for entry in hits)
    assert report["zip_pyc_members"] == 1


def test_scanner_needle_split_across_chunk_boundary(tmp_path):
    dp = _driver()
    needle = b"/Users/buildbot-home"
    blob = b"\x00" * (4 * 1024 * 1024 - 10) + needle + b"\x00" * 64
    (tmp_path / "big.bin").write_bytes(blob)
    report = dp.scan_tree(tmp_path, {"home": needle})
    assert "big.bin" in report["hits"]


def test_sanitizer_removes_direct_url_and_reports_leak(tmp_path):
    dp = _driver()
    dist_info = tmp_path / "arxmcp-0.1.0.dist-info"
    dist_info.mkdir(parents=True)
    (dist_info / "direct_url.json").write_text(
        json.dumps({"url": "file:///tmp/arxmcp-wheel-check/arxmcp.whl"}),
        encoding="utf-8",
    )
    report = dp.sanitize_direct_url(tmp_path)
    assert report["found"] is True
    assert report["leak_observed"] is True
    assert not (dist_info / "direct_url.json").exists()
    again = dp.sanitize_direct_url(tmp_path)
    assert again["found"] is False


def test_manifest_diff_catches_content_membership_and_mode(tmp_path):
    dp = _driver()
    a, b = tmp_path / "a", tmp_path / "b"
    for root in (a, b):
        (root / "sub").mkdir(parents=True)
        (root / "same.txt").write_text("same", encoding="utf-8")
        (root / "sub" / "content.bin").write_bytes(b"one")
    (b / "sub" / "content.bin").write_bytes(b"two")
    (b / "only-in-b").write_text("x", encoding="utf-8")
    (a / "mode.sh").write_text("#!/bin/sh\n", encoding="utf-8")
    (b / "mode.sh").write_text("#!/bin/sh\n", encoding="utf-8")
    (b / "mode.sh").chmod(0o755)
    diff = dp.manifest_diff(dp.file_manifest(a), dp.file_manifest(b))
    assert diff == ["mode.sh", "only-in-b", "sub/content.bin"]


# --- the packaging gate (requires_desktop_package; `make desktop-package-check`) ---


@pytest.fixture(scope="module")
def packaged():
    """Provision + TWO independent builds; module-scoped so every gate test
    asserts against the same evidence run. Prerequisite failures RAISE — under
    DESKTOP_PACKAGE_GATE a skip would fail the session anyway (m6 precedent)."""
    if shutil.which("uv") is None:
        raise RuntimeError(
            "uv is required for the desktop packaging gate; install uv and re-run "
            "`make desktop-package-check`"
        )
    dp = _driver()
    report = dp.verify_determinism(dp.DEFAULT_ROOT)
    return dp, report


@pytest.mark.requires_desktop_package
def test_two_builds_are_byte_identical_within_pinned_exceptions(packaged):
    """AC1: two independent PyInstaller invocations from the same tree, fresh
    work/dist paths each, per-file manifests diffed against the CLOSED set."""
    dp, report = packaged
    det = report["determinism"]
    assert det["manifest_entries"] >= 4000, "suspiciously small bundle manifest"
    unexpected = set(det["differing"]) - dp.NONDETERMINISTIC_EXCEPTIONS
    assert not unexpected, (
        f"NEW nondeterministic paths (grow the pinned set only with a per-entry "
        f"'why unavoidable' rationale): {sorted(unexpected)}"
    )


@pytest.mark.requires_desktop_package
def test_frozen_latex2mathml_output_matches_source_tree(packaged, tmp_path):
    """AC2: the bundled probe converts the SAME fixtures the source tree
    converts in this very process; outputs must be byte-identical, and the
    bundled symbol table must hash-match the source venv's copy."""
    import latex2mathml.converter as converter_mod

    dp, report = packaged
    bundle = Path(report["bundle"])
    proc = subprocess.run(
        [str(bundle / dp.PROBE_EXE)],
        input=json.dumps({"latex": LATEX_FIXTURES}),
        capture_output=True,
        text=True,
        env=_frozen_env(tmp_path),
        timeout=180,
    )
    assert proc.returncode == 0, f"probe failed: {proc.stderr[-2000:]}"
    frozen = json.loads(proc.stdout)
    for latex in LATEX_FIXTURES:
        expected = converter_mod.convert(latex)
        assert frozen["conversions"][latex].encode() == expected.encode(), (
            f"frozen conversion diverged for {latex!r}"
        )
    source_table = (
        Path(converter_mod.__file__).resolve().parent / "unimathsymbols.txt"
    )
    assert (
        frozen["symbol_table_sha256"]
        == hashlib.sha256(source_table.read_bytes()).hexdigest()
    )
    assert frozen["symbol_table_bytes"] == source_table.stat().st_size


@pytest.mark.requires_desktop_package
def test_frozen_spawn_reexec_never_reenters_main(packaged, tmp_path):
    """AC3 dynamic half, on the REAL frozen executable — never a mocked
    freeze_support. main() ignores argv entirely, so absent freeze_support()
    a ``--multiprocessing-fork`` re-exec would behave exactly like the control
    arm: enter main() as a duplicate top-level desktop child. The control arm
    proves what entering main() looks like on this binary (a traceback frame
    ``in main``; today it dies inside ``executable_identity`` because the
    frozen entry has no on-disk source — a known, separately tracked frozen
    gap). The fork-flagged arm must never reach main(): freeze_support
    intercepts and multiprocessing's spawn_main dies on the unfed pipe with
    EOFError instead."""
    dp, report = packaged
    exe = str(Path(report["bundle"]) / dp.CHILD_EXE)
    env = _frozen_env(tmp_path)

    control = subprocess.run(
        [exe],
        stdin=subprocess.DEVNULL,
        capture_output=True,
        env=env,
        timeout=180,
    )
    assert control.returncode != 0
    assert b", in main" in control.stderr, (
        f"control arm never entered main(); stderr: {control.stderr[-2000:]}"
    )
    assert b"EOFError" not in control.stderr

    read_fd, write_fd = os.pipe()
    try:
        os.set_inheritable(read_fd, True)
        proc = subprocess.Popen(
            [exe, "--multiprocessing-fork", f"pipe_handle={read_fd}"],
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            env=env,
            pass_fds=(read_fd,),
        )
    finally:
        os.close(read_fd)
    os.close(write_fd)  # child's pipe read hits EOF; spawn_main dies unfed
    _, stderr = proc.communicate(timeout=180)
    assert b", in main" not in stderr, (
        f"fork re-exec fell through to main() — duplicate top-level process; "
        f"stderr: {stderr[-2000:]}"
    )
    assert b"EOFError" in stderr, (
        f"expected multiprocessing spawn_main to engage and hit pipe EOF; "
        f"stderr: {stderr[-2000:]}"
    )


@pytest.mark.requires_desktop_package
def test_no_direct_url_leak_in_bundle(packaged):
    """AC4: the leak must be OBSERVED pre-sanitize on the real toolchain path
    (a check that passes because the file never existed proves nothing), and
    the frozen tree must carry no file:// build-machine URL."""
    dp, report = packaged
    assert report["direct_url"]["leak_observed"] is True
    bundle = Path(report["bundle"])
    stray = list(bundle.rglob("direct_url.json"))
    assert stray == [], f"direct_url.json shipped in the bundle: {stray}"


@pytest.mark.requires_desktop_package
def test_bundle_carries_no_build_machine_paths(packaged):
    """AC5: zero occurrences of temp root / $HOME / username across ALL
    regular files — plus nested zips and the executables' embedded PYZ, where
    compiled .pyc bytes (co_filename) hide from a raw grep. Coverage floors +
    the bytes-read tripwire prove the scan actually opened everything."""
    _, report = packaged
    scan = report["scan"]
    assert scan["hits"] == {}
    assert scan["bytes_scanned"] == scan["lstat_bytes"]
    assert scan["files_scanned"] >= 4000
    assert scan["native_files"] >= 100
    assert scan["zip_pyc_members"] >= 100
    assert scan["embedded"]["pyc_entries"] >= 5000


@pytest.mark.requires_desktop_package
def test_bundle_executables_exist_and_are_signed(packaged):
    """The artifact later signing work consumes: both executables present and
    carrying a valid (ad-hoc at this stage) macOS signature."""
    dp, report = packaged
    bundle = Path(report["bundle"])
    for name in (dp.CHILD_EXE, dp.PROBE_EXE):
        exe = bundle / name
        assert exe.is_file() and os.access(exe, os.X_OK)
    if sys.platform == "darwin":
        proc = subprocess.run(
            ["/usr/bin/codesign", "--verify", "--strict", str(bundle / dp.CHILD_EXE)],
            capture_output=True,
            text=True,
            timeout=120,
        )
        assert proc.returncode == 0, f"codesign verify failed: {proc.stderr}"
