/* generated by `npm run gen:api` from ../openapi.json (IF-1)
 * source-sha256: 88d9f86987019176b5131c776731acc25018fc0e6cdc5a0dd544667d63ad036b
 * DO NOT EDIT BY HAND. */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/repair-registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Repair Registry V1
         * @description Registry repair — direct delegate (already JSON) + stamp.
         */
        post: operations["repair_registry_v1_api_v1_admin_repair_registry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capabilities/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Profiles
         * @description List effective profiles (the synthesized ``default`` included
         *     when the operator has not overridden it).
         */
        get: operations["list_profiles_api_v1_capabilities_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capabilities/profiles/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upsert Profile
         * @description Create or replace one profile; effective immediately (cache
         *     invalidated inline).
         */
        put: operations["upsert_profile_api_v1_capabilities_profiles__name__put"];
        post?: never;
        /**
         * Delete Profile
         * @description Remove one profile. Deleting an operator-defined ``default``
         *     restores the synthesized permissive default. 404 when absent.
         */
        delete: operations["delete_profile_api_v1_capabilities_profiles__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events Stream
         * @description The single multiplexed live stream (gap R8; AC-A.14; IF-2).
         *
         *     ``topics`` is a comma-separated subset of
         *     ``logs,requests,sessions,ingest``; unknown names are a 422 (a
         *     typo'd topic silently delivering nothing would be a debugging
         *     trap). Per-client queue cap + drop-oldest are enforced in
         *     :class:`server.observability.events.EventBus` — a stalled
         *     consumer's server-side footprint is bounded by the queue cap.
         *
         *     The response is exempt from ``BodySizeCapMiddleware`` (the stream
         *     is unbounded by design — see the segment-exact carve-out in
         *     ``server/main.py::_is_exempt_path``; flagged for the issue-#9
         *     scope amendment).
         */
        get: operations["events_stream_api_v1_events_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Ingest Events
         * @description Additive ingest/parse stage events (gap R4; AC-A.15). The
         *     legacy tri-state poll surfaces are untouched — this ring is a new,
         *     parallel read model.
         */
        get: operations["list_ingest_events_api_v1_ingest_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs/tail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Logs Tail
         * @description Snapshot of the in-process log ring (gap R2; AC-A.12).
         *
         *     Every record here passed ``RedactionFilter`` BEFORE entering the
         *     ring (handler-level filter — the ordering contract in
         *     ``logging_setup``). ``level`` filters case-insensitively on the
         *     record's level name (a facet, not a query language).
         */
        get: operations["logs_tail_api_v1_logs_tail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notebooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Notebooks V1
         * @description List notebooks, paginated, ordered ``created_at DESC, slug ASC``
         *     (the store's stable ordering).
         */
        get: operations["list_notebooks_v1_api_v1_notebooks_get"];
        put?: never;
        /**
         * Create Notebook V1
         * @description Create a notebook. Delegates to the shared handler's JSON branch
         *     (409 on duplicate slug; 422 on bad slug/category).
         */
        post: operations["create_notebook_v1_api_v1_notebooks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notebooks/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Notebook V1
         * @description Metadata-only delete (404 if absent). Always 204 — the legacy
         *     handler's HX-Request 200-empty-body branch is unreachable here.
         */
        delete: operations["delete_notebook_v1_api_v1_notebooks__slug__delete"];
        options?: never;
        head?: never;
        /**
         * Rename Notebook V1
         * @description Rename a notebook's ``display_name`` — JSON alias of the legacy
         *     fragment-only PATCH. Same validation order and store call; returns
         *     the stored (control-char-stripped) value instead of an HTML swap.
         */
        patch: operations["rename_notebook_v1_api_v1_notebooks__slug__patch"];
        trace?: never;
    };
    "/api/v1/notebooks/{slug}/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discover Papers V1
         * @description Run topic discovery — JSON alias of the legacy fragment-only
         *     POST. Same driver, dedup, and error translation (422 unconfigured;
         *     502 arXiv failure); returns the candidate list as JSON. The
         *     candidate QUEUE remains EPHEMERAL (propose-only; no junction rows
         *     are written); real paper metadata is populated separately by the
         *     per-notebook arXiv-Atom backfill (``tools/notebook_metadata_backfill.py``
         *     → ``server.paper_metadata_store``).
         */
        post: operations["discover_papers_v1_api_v1_notebooks__slug__discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notebooks/{slug}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Notebook V1
         * @description Deterministic notebook tar — direct delegate. Binary response;
         *     the format version rides in ``X-Arxmcp-Format-Version`` (the tar's
         *     internal ``manifest.json`` carries the bundle's own
         *     ``format_version`` independently).
         */
        get: operations["export_notebook_v1_api_v1_notebooks__slug__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notebooks/{slug}/graph/neighbors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Graph Neighbors V1
         * @description Citation-graph neighbors of ``paper_id`` — the REST read twin of
         *     the MCP ``cite_neighbors`` tool (AC-A.20).
         *
         *     Mirrors the MCP handler's envelope vocabulary and degradation
         *     semantics exactly (``server/handlers/citations.py``,
         *     verification-feedback-m1):
         *
         *     - ``graph_status: "absent"`` — the Kùzu DB path does not exist
         *       (graph not ingested). Empty ``neighbors``, HTTP 200.
         *     - ``graph_status: "unavailable"`` — the path exists but is not a
         *       queryable Kùzu graph (stray dir / corrupt / half-ingested DB;
         *       Kùzu raises RuntimeError). Empty ``neighbors``, HTTP 200,
         *       logged at WARNING so the operator failure is observable.
         *     - ``graph_status: "present"`` — queried successfully; ``neighbors``
         *       rows carry the same ``CitationNeighbor`` field vocabulary as the
         *       MCP tool (``paper_id``/``chunk_id``/``edge_kind``/
         *       ``hop_distance``/``source``/``confidence``, ordered
         *       ``(hop_distance ASC, paper_id ASC)``).
         *
         *     Differences owned by this surface (documented, deliberate): the
         *     query key is ``paper_id`` (junction rows, not chunk ids — the MCP
         *     tool's chunk_id parse happens before the shared library entry
         *     anyway) and the version stamp is ``format_version`` (the
         *     ``/api/v1`` envelope) rather than the MCP ``corpus_version`` echo,
         *     which requires warm retrieval Resources this read-only surface
         *     must not depend on (the graph is queryable in bootstrap mode).
         *
         *     F2 path-validation contract: the Kùzu/LanceDB paths come from
         *     ``app.state.config`` — NEVER from request input. The client
         *     controls only ``paper_id`` (regex-validated), ``direction``/
         *     ``depth``/``limit`` (enum/bounds-validated).
         */
        get: operations["graph_neighbors_v1_api_v1_notebooks__slug__graph_neighbors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notebooks/{slug}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Notebook Health V1
         * @description Per-notebook drift report — direct delegate (already JSON) + stamp.
         */
        get: operations["notebook_health_v1_api_v1_notebooks__slug__health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notebooks/{slug}/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Ingest V1
         * @description Spawn a background ingest — JSON alias of the legacy
         *     fragment-returning trigger. Same sequencing (validate → 409-check →
         *     INSERT row → spawn task) and the same two-layer collision check;
         *     returns the run row reference instead of an htmx fragment.
         *
         *     stage2/arx-a45 (AC-A.18): kind-aware dispatch via the SAME
         *     ``_ingest_dispatch_kwargs`` helper as the legacy trigger — a
         *     textbook notebook spawns ``tools.notebook_textbook_ingest`` with
         *     its stored ``textbook_chunker``; arxiv-kind keeps the papers.txt
         *     bulk ingest. One helper, two surfaces, zero drift.
         */
        post: operations["trigger_ingest_v1_api_v1_notebooks__slug__ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notebooks/{slug}/ingest/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest Ingest V1
         * @description Latest ingest-run state as JSON. Plain 200 always (no HTTP 286 —
         *     that status is an htmx polling-transport artifact of the legacy
         *     surface); ``terminal`` tells a JSON poller when to stop.
         *
         *     ``status: "none"`` when the notebook has no runs yet.
         */
        get: operations["latest_ingest_v1_api_v1_notebooks__slug__ingest_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notebooks/{slug}/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Papers V1
         * @description List a notebook's paper junction rows, paginated, ordered
         *     ``added_at DESC, paper_id ASC`` (the store's stable ordering).
         */
        get: operations["list_papers_v1_api_v1_notebooks__slug__papers_get"];
        put?: never;
        /**
         * Add Paper V1
         * @description Add a paper by arXiv URL. Delegates to the shared handler's JSON
         *     branch (422 bad URL; 404 no notebook; 409 duplicate).
         */
        post: operations["add_paper_v1_api_v1_notebooks__slug__papers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notebooks/{slug}/papers/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Paper V1
         * @description Upload an ar5iv HTML (arxiv-kind) or PDF (textbook-kind) file.
         *
         *     Delegates the ENTIRE validated pipeline (per-kind caps, magic-byte
         *     sniff, 5-vector PDF preflight, atomic write, junction insert, parse
         *     scheduling) to the shared handler, then translates its
         *     fragment-response status into a JSON body:
         *
         *     - 201 → ``result: "created"`` (new junction row + file written)
         *     - 200 → ``result: "updated_existing"`` (row existed; file
         *       atomically overwritten — the legacy handler's idempotent-upload
         *       contract)
         */
        post: operations["upload_paper_v1_api_v1_notebooks__slug__papers_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notebooks/{slug}/papers/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Paper V1
         * @description Remove a paper junction row — direct delegate (already JSON/204).
         */
        delete: operations["remove_paper_v1_api_v1_notebooks__slug__papers__paper_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notebooks/{slug}/parse-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Parse Status V1
         * @description Textbook-parse status — direct delegate (already JSON) + stamp.
         */
        get: operations["parse_status_v1_api_v1_notebooks__slug__parse_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notebooks/{slug}/reconcile-marker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reconcile Marker V1
         * @description Marker reconcile — direct delegate (already JSON) + stamp.
         */
        post: operations["reconcile_marker_v1_api_v1_notebooks__slug__reconcile_marker_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notebooks/{slug}/topic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Topic V1
         * @description Update topic metadata — JSON alias of the legacy fragment-only
         *     PATCH. Same category enum gate + control-char stripping.
         */
        patch: operations["update_topic_v1_api_v1_notebooks__slug__topic_patch"];
        trace?: never;
    };
    "/api/v1/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Request Events
         * @description Last-N request events, newest first (gap R1; AC-A.11).
         *
         *     ``since_seq`` returns only events strictly newer than the cursor —
         *     the polling degraded mode's gap-free catch-up (within ring
         *     capacity; a seq jump larger than the ring means events aged out).
         */
        get: operations["list_request_events_api_v1_requests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description Read-only projection of the MCP session registry with per-cap
         *     remaining counts (gaps R3/R7; AC-A.13). The registry itself stays
         *     module-private in :mod:`server.session` — this endpoint serializes
         *     a point-in-time copy and never mutates state.
         */
        get: operations["list_sessions_api_v1_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tool-calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tool Calls
         * @description Newest-first page over the append-only ``tool_calls`` audit
         *     store (AC-A.9's read side). 503 while the store is not yet bound
         *     (startup) — a probe-friendly signal, not an error state.
         */
        get: operations["list_tool_calls_api_v1_tool_calls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bridge/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bridge Contracts
         * @description The contract-registry handshake (finding 06 §2.5.2 item 4).
         *
         *     Response shape (all fields always present)::
         *
         *         {
         *           "format_version": 1,
         *           "registry_status": "absent" | "registry" | "scan"
         *                              | "malformed_registry",
         *           "envelope": {"version": <str|null>,
         *                         "schema": <filename|null>,
         *                         "schema_sha256": <hex|null>} | null,
         *           "artifact_types": {
         *             "<type-id>": {"version": <str|null>,
         *                            "schema": <filename|null>,
         *                            "schema_sha256": <hex|null>},
         *             ...
         *           },
         *           "count": <int>
         *         }
         *
         *     ``registry_status: "absent"`` with an empty map is the
         *     empty-registry envelope served until WS-C publishes ``contracts/``.
         *
         *     ``envelope`` (stage3/cross-r1) is the top-level substrate-wrapper
         *     entry from ``registry.json`` (``null`` when there is no registry /
         *     no envelope block). It is served alongside the artifact types so the
         *     consumer's preflight can verify the six-field substrate block — the
         *     anti-spike-1/2/3 core — whose bytes never move in any artifact-type
         *     schema (they reference the envelope by opaque URN ``$ref``).
         *     ``format_version`` stays 1: the field is purely additive and
         *     older consumers ignore it.
         */
        get: operations["bridge_contracts_bridge_contracts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe.
         *
         *     Always 200 if the process can respond at all. Does NOT inspect
         *     resource warm state — a process loading the BGE-M3 model still
         *     returns 200 here (and 503 from ``/readyz``). The brief AC:
         *     *"returns 200 before readiness."*
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness probe.
         *
         *     Returns 200 only after :meth:`server.resources.Resources.startup`
         *     has completed and ``Resources.warm`` is True. Returns 503 with a
         *     JSON body naming the un-warm resources during the window between
         *     process start and readiness.
         *
         *     The body shape is documented for ops dashboards:
         *
         *         {"status": "ready" | "not_ready",
         *          "warm": {"embedder": bool, "lancedb": bool, "reranker": bool}}
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Status Endpoint
         * @description Operability snapshot as IETF ``application/health+json``
         *     (notebook-ops-hardening-m4).
         *
         *     A SUPERSET of ``/readyz``: ``status: pass|warn|fail`` + per-component
         *     ``checks`` (embedder, lancedb, corpus:version, notebooks:count,
         *     disk:utilization, backup:time, process:uptime). HTTP 200 for ``pass`` and
         *     ``warn`` (serving, possibly degraded), 503 for ``fail`` (not warm). Unlike
         *     ``/readyz`` (which 503s on the degraded case), ``/status`` reports the
         *     degraded state as ``warn`` with a 200 so an operator/badge sees
         *     "serving-but-degraded" distinctly from "down". ``/readyz`` is unchanged.
         *
         *     NOT an MCP tool — no tool-schema / BP1 impact. Consumed by ``make status``
         *     + the ``/ui/status-badge`` poll.
         */
        get: operations["status_endpoint_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_paper_v1_api_v1_notebooks__slug__papers_upload_post */
        Body_upload_paper_v1_api_v1_notebooks__slug__papers_upload_post: {
            /** File */
            file: string;
            /** Paper Id */
            paper_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * NotebookCreate
         * @description Body for ``POST /ui/api/notebooks``.
         *
         *     Only ``slug`` is required; ``display_name`` defaults to ``""`` and
         *     ``notebook_kind`` defaults to ``"arxiv"``. ``lancedb_path`` is
         *     AUTO-DERIVED from ``NOTEBOOKS_BASE / slug / "lancedb"`` (the caller
         *     MUST NOT supply a custom path — that would let a buggy or
         *     malicious client steer a notebook at any on-disk location
         *     bypassing the per-notebook directory contract from m6).
         *
         *     textbook-ingest-m3: ``notebook_kind`` ``str`` with Pydantic
         *     pattern ``^(arxiv|textbook)$``. Operator opt-in for the textbook-
         *     corpus path (parser e2 + chunker e3 ship later); arXiv remains the
         *     default. The pattern validation rejects ``"freeform-garbage"`` at
         *     the route layer before it reaches the SQLite writer.
         */
        NotebookCreate: {
            /**
             * Chunker
             * @default html
             */
            chunker: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Discovery Category
             * @default
             */
            discovery_category: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /**
             * Notebook Kind
             * @default arxiv
             */
            notebook_kind: string;
            /** Slug */
            slug: string;
        };
        /**
         * NotebookRename
         * @description Body for ``PATCH /ui/api/notebooks/{slug}`` (notebook-surface-expansion-m2).
         *
         *     Carries ONLY ``display_name`` — slug / notebook_kind / parse_status are
         *     NOT acceptable PATCH fields (mass-assignment defense; the store method
         *     takes only ``(slug, display_name)``). Same ``max_length=256`` bound as
         *     ``NotebookCreate`` → FastAPI returns 422 on an over-long name before the
         *     handler body runs. NO ``min_length``: an empty string is a valid value
         *     (clears the display name; renders as ``—``).
         */
        NotebookRename: {
            /** Display Name */
            display_name: string;
        };
        /**
         * NotebookTopicUpdate
         * @description Body for ``PATCH /ui/api/notebooks/{slug}/topic`` (notebook-paper-discovery-m1).
         *
         *     Carries ONLY the two topic-metadata fields — ``slug`` /
         *     ``display_name`` / ``notebook_kind`` / ``parse_status`` are NOT
         *     acceptable here (mass-assignment defense; the dedicated ``/topic``
         *     sub-route keeps the rename endpoint's contract untouched). Both
         *     fields accept an empty string (clears the topic). ``discovery_category``
         *     is enum-validated in the handler via ``_validate_discovery_category``;
         *     the ``max_length`` bounds here are only defense-in-depth.
         */
        NotebookTopicUpdate: {
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Discovery Category
             * @default
             */
            discovery_category: string;
        };
        /**
         * PaperAdd
         * @description Body for ``POST /ui/api/notebooks/{slug}/papers``.
         */
        PaperAdd: {
            /** Arxiv Url */
            arxiv_url: string;
        };
        /**
         * ProfileUpsert
         * @description PUT body for one profile. ``extra="forbid"`` is the AC-A.10
         *     tripwire: a raw ``token`` member is an unknown field → 422.
         */
        ProfileUpsert: {
            /**
             * Caps
             * @description Per-tool per-session caps (tool -> max calls), superseding the built-in 3-search/4-chunk constants.
             */
            caps?: {
                [key: string]: number;
            } | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Notebooks
             * @description Notebook-slug allowlist; null = unscoped.
             */
            notebooks?: string[] | null;
            /**
             * Token Sha256
             * @description SHA-256 hex digest of the bearer token. NEVER the token value. Omit for the token-less default profile.
             */
            token_sha256?: string | null;
            /**
             * Tools
             * @description Tool allowlist; null = all tools.
             */
            tools?: string[] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    repair_registry_v1_api_v1_admin_repair_registry_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_profiles_api_v1_capabilities_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    upsert_profile_api_v1_capabilities_profiles__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_profile_api_v1_capabilities_profiles__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_stream_api_v1_events_stream_get: {
        parameters: {
            query?: {
                topics?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ingest_events_api_v1_ingest_events_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                since_seq?: number | null;
                slug?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logs_tail_api_v1_logs_tail_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                since_seq?: number | null;
                level?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notebooks_v1_api_v1_notebooks_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_notebook_v1_api_v1_notebooks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotebookCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_notebook_v1_api_v1_notebooks__slug__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_notebook_v1_api_v1_notebooks__slug__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotebookRename"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_papers_v1_api_v1_notebooks__slug__discover_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_notebook_v1_api_v1_notebooks__slug__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/x-tar": unknown;
                };
            };
            /** @description notebook not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description malformed slug */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    graph_neighbors_v1_api_v1_notebooks__slug__graph_neighbors_get: {
        parameters: {
            query: {
                /** @description arXiv paper id */
                paper_id: string;
                /** @description Graph traversal direction */
                direction?: string;
                /** @description Hop count */
                depth?: number;
                /** @description Max neighbors returned */
                limit?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notebook_health_v1_api_v1_notebooks__slug__health_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_ingest_v1_api_v1_notebooks__slug__ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_ingest_v1_api_v1_notebooks__slug__ingest_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_papers_v1_api_v1_notebooks__slug__papers_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_paper_v1_api_v1_notebooks__slug__papers_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaperAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_paper_v1_api_v1_notebooks__slug__papers_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_paper_v1_api_v1_notebooks__slug__papers_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_paper_v1_api_v1_notebooks__slug__papers__paper_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_status_v1_api_v1_notebooks__slug__parse_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reconcile_marker_v1_api_v1_notebooks__slug__reconcile_marker_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_topic_v1_api_v1_notebooks__slug__topic_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotebookTopicUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_request_events_api_v1_requests_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                since_seq?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_v1_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tool_calls_api_v1_tool_calls_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bridge_contracts_bridge_contracts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    status_endpoint_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
