#!/bin/sh
exec /usr/bin/python3 -c '
import sys,json,time
line=sys.stdin.buffer.readline()
tok=json.loads(line)["startup_token"]
sys.stdout.write("{TOKEN="+tok+"} and again "+tok+" and UPPER "+tok.upper()+" and partial "+tok[:32]+"\n")
sys.stdout.flush()
time.sleep(300)
'
